create table public.bancoconta (
  id bigint generated by default as identity not null,
  titulo text not null,
  created_at timestamp with time zone not null default now(),
  valorinicial real not null,
  agencia text null,
  contanumero text null,
  tipo public.banco_tipo not null default 'CORRENTE'::banco_tipo,
  proprietario text null,
  empresa_id integer null,
  updated_at timestamp with time zone not null default now(),
  ativo boolean null default true,
  constraint banco_conta_pkey primary key (id),
  constraint bancoconta_empresa_id_fkey foreign KEY (empresa_id) references empresa (id)
) TABLESPACE pg_default;

create table public.categoriaservico (
  id integer generated always as identity not null,
  nome character varying not null,
  descricao character varying null,
  constraint categoriaservico_pkey primary key (id)
) TABLESPACE pg_default;

create table public.categoriatransacao (
  id integer generated always as identity not null,
  nome text not null,
  descricao text null,
  ativo boolean not null default true,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  constraint categoriatransacao_pkey primary key (id),
  constraint categoria_transacao_nome_key unique (nome)
) TABLESPACE pg_default;

create table public.checklist (
  id integer generated always as identity not null,
  ordemservicoid integer not null,
  item character varying not null,
  status public.enum_status_checklist not null default 'OK'::enum_status_checklist,
  observacao character varying null,
  createdat timestamp without time zone null default now(),
  constraint checklist_pkey primary key (id),
  constraint fk_checklist_ordem_servico foreign KEY (ordemservicoid) references ordemservico (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.checklist_modelo (
  id integer generated always as identity not null,
  nome character varying not null,
  descricao character varying null,
  categoria character varying null,
  ativo boolean not null default true,
  criado_em timestamp without time zone not null default now(),
  atualizado_em timestamp without time zone not null default now(),
  constraint checklist_modelo_pkey primary key (id),
  constraint checklist_modelo_nome_key unique (nome)
) TABLESPACE pg_default;

create trigger trg_checklist_modelo_updated BEFORE
update on checklist_modelo for EACH row
execute FUNCTION set_checklist_modelo_updated_at ();

create table public.checklist_modelo_item (
  id integer generated always as identity not null,
  modelo_id integer not null,
  titulo character varying not null,
  descricao character varying null,
  categoria character varying null,
  obrigatorio boolean not null default false,
  ordem integer not null default 0,
  constraint checklist_modelo_item_pkey primary key (id),
  constraint checklist_modelo_item_modelo_id_fkey foreign KEY (modelo_id) references checklist_modelo (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_checklist_modelo_item_modelo on public.checklist_modelo_item using btree (modelo_id) TABLESPACE pg_default;

create table public.cliente (
  id integer generated always as identity not null,
  tipopessoa public.enum_tipopessoa not null,
  cpfcnpj character varying not null,
  nomerazaosocial character varying not null,
  email character varying not null,
  telefone character varying not null,
  endereco character varying null,
  cidade character varying not null,
  estado character varying not null,
  cep character varying null,
  inscricaoestadual character varying null,
  inscricaomunicipal character varying null,
  codigomunicipio character varying null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  status public.enum_status_cliente null default 'ATIVO'::enum_status_cliente,
  endereconumero text null,
  enderecocomplemento text null,
  bairro text null,
  constraint cliente_pkey primary key (id),
  constraint cliente_cpfcnpj_key unique (cpfcnpj),
  constraint cliente_nomerazaosocial_key unique (nomerazaosocial),
  constraint cliente_telefone_key unique (telefone)
) TABLESPACE pg_default;

create index IF not exists idx_cliente_cpfcnpj on public.cliente using btree (cpfcnpj) TABLESPACE pg_default;

create table public.empresa (
  id integer generated always as identity not null,
  cnpj character varying not null,
  razaosocial character varying not null,
  nomefantasia character varying null,
  inscricaoestadual character varying null,
  inscricaomunicipal character varying null,
  endereco character varying not null,
  codigomunicipio character varying not null,
  regimetributario character varying not null,
  certificadocaminho character varying null,
  cschomologacao character varying null,
  cscproducao character varying null,
  ambiente character varying null default 'HOMOLOGACAO'::character varying,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  bairro character varying null,
  numero character varying null,
  complemento character varying null,
  cep character varying null,
  uf character varying(2) null,
  codigopais character varying null default '1058'::character varying,
  nomepais character varying null default 'BRASIL'::character varying,
  telefone character varying null,
  cnae character varying null,
  inscricaoestadualst character varying null,
  certificadosenha character varying null,
  constraint empresa_pkey primary key (id),
  constraint empresa_cnpj_key unique (cnpj),
  constraint empresa_ambiente_check check (
    (
      (ambiente)::text = any (
        (
          array[
            'HOMOLOGACAO'::character varying,
            'PRODUCAO'::character varying
          ]
        )::text[]
      )
    )
  ),
  constraint empresa_regimetributario_check check (
    (
      (regimetributario)::text = any (
        (
          array[
            '1'::character varying,
            '2'::character varying,
            '3'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create table public.fornecedor (
  id integer generated always as identity not null,
  cpfcnpj character varying not null,
  nomerazaosocial text not null,
  nomefantasia character varying null,
  endereco character varying null,
  cidade character varying null,
  estado character varying null,
  cep character varying null,
  contato character varying null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  endereconumero text null,
  enderecocomplemento text null,
  bairro text null,
  ativo boolean not null default true,
  constraint fornecedor_pkey primary key (id),
  constraint fornecedor_cnpj_key unique (cpfcnpj)
) TABLESPACE pg_default;

create table public.fornecedorprodutos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  fornecedorid integer not null,
  produtoid integer not null,
  codigofornecedor text not null,
  ultimovalordecompra numeric null,
  constraint fornecedorprodutos_pkey primary key (id),
  constraint fornecedorprodutos_fornecedorid_fkey foreign KEY (fornecedorid) references fornecedor (id),
  constraint fornecedorprodutos_produtoid_fkey foreign KEY (produtoid) references produto (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.imagemvistoria (
  id integer generated always as identity not null,
  checklistid integer not null,
  url character varying not null,
  descricao character varying null,
  createdat timestamp without time zone null default now(),
  constraint imagemvistoria_pkey primary key (id),
  constraint fk_imagem_vistoria_checklist foreign KEY (checklistid) references checklist (id)
) TABLESPACE pg_default;

create table public.nfe (
  id bigserial not null,
  modelo public.enum_modelo_nfe not null default 'NFE'::enum_modelo_nfe,
  serie integer not null,
  numero integer not null,
  chave_acesso character(44) not null,
  ambiente public.enum_ambiente_nfe not null default 'HOMOLOGACAO'::enum_ambiente_nfe,
  status public.enum_status_nfe not null default 'RASCUNHO'::enum_status_nfe,
  ordemservicoid integer null,
  vendaid integer null,
  clienteid integer not null,
  dataemissao timestamp with time zone not null,
  dataautorizacao timestamp with time zone null,
  protocolo text null,
  total_produtos numeric(14, 2) not null default 0,
  total_servicos numeric(14, 2) not null default 0,
  total_nfe numeric(14, 2) not null default 0,
  xml_assinado text null,
  xml_autorizado text null,
  justificativacancelamento text null,
  createdat timestamp with time zone not null default now(),
  updatedat timestamp with time zone not null default now(),
  empresaid integer not null,
  icms text null,
  cfop text null,
  constraint nfe_pkey primary key (id),
  constraint nfe_chave_acesso_key unique (chave_acesso),
  constraint nfe_clienteid_fkey foreign KEY (clienteid) references cliente (id),
  constraint nfe_empresaid_fkey foreign KEY (empresaid) references empresa (id),
  constraint nfe_ordemservicoid_fkey foreign KEY (ordemservicoid) references ordemservico (id) on delete set null,
  constraint nfe_vendaid_fkey foreign KEY (vendaid) references venda (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_nfe_cliente on public.nfe using btree (clienteid) TABLESPACE pg_default;

create index IF not exists idx_nfe_ordemservico on public.nfe using btree (ordemservicoid) TABLESPACE pg_default;

create index IF not exists idx_nfe_venda on public.nfe using btree (vendaid) TABLESPACE pg_default;

create index IF not exists idx_nfe_status on public.nfe using btree (status) TABLESPACE pg_default;

create table public.nfe_config (
  id bigserial not null,
  empresaid bigint not null,
  modelo public.enum_modelo_nfe not null default 'NFE'::enum_modelo_nfe,
  serie integer not null default 1,
  ultimo_numero integer not null default 0,
  ambiente public.enum_ambiente_nfe not null default 'HOMOLOGACAO'::enum_ambiente_nfe,
  tp_emis smallint not null default 1,
  versao_layout character varying(5) not null default '4.00'::character varying,
  tipo_impressao_danfe smallint not null default 1,
  permitir_homologacao boolean not null default true,
  permitir_producao boolean not null default true,
  createdat timestamp with time zone not null default now(),
  updatedat timestamp with time zone not null default now(),
  constraint nfe_config_pkey primary key (id),
  constraint nfe_config_empresaid_key unique (empresaid),
  constraint nfe_config_empresaid_fkey foreign KEY (empresaid) references empresa (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.nfe_item (
  id bigserial not null,
  nfe_id bigint not null,
  n_item integer not null,
  produtoid integer null,
  descricao text not null,
  ncm text null,
  cfop text not null,
  csosn text null,
  cest text null,
  unidade public.unidade_medida not null,
  quantidade numeric(14, 4) not null,
  valor_unitario numeric(14, 10) not null,
  valor_total numeric(14, 2) not null,
  valor_desconto numeric(14, 2) null,
  aliquotaicms numeric(5, 2) null,
  valor_bc_icms numeric(14, 2) null,
  valor_icms numeric(14, 2) null,
  cst_pis text null,
  aliquota_pis numeric(5, 2) null,
  valor_pis numeric(14, 2) null,
  cst_cofins text null,
  aliquota_cofins numeric(5, 2) null,
  valor_cofins numeric(14, 2) null,
  createdat timestamp with time zone not null default now(),
  updatedat timestamp with time zone not null default now(),
  cst text null,
  constraint nfe_item_pkey primary key (id),
  constraint nfe_item_nfe_id_fkey foreign KEY (nfe_id) references nfe (id) on delete CASCADE,
  constraint nfe_item_produtoid_fkey foreign KEY (produtoid) references produto (id)
) TABLESPACE pg_default;

create index IF not exists idx_nfe_item_nfe on public.nfe_item using btree (nfe_id) TABLESPACE pg_default;

create index IF not exists idx_nfe_item_produto on public.nfe_item using btree (produtoid) TABLESPACE pg_default;

create table public.nfse_config (
  empresa_id integer not null,
  provedor text null,
  inscricao_municipal text null,
  serie_rps text null,
  usuario text null,
  senha text null,
  token text null,
  certificado_a1_base64 text null,
  senha_certificado text null,
  updated_at timestamp with time zone null default now(),
  constraint nfse_config_pkey primary key (empresa_id),
  constraint nfse_config_empresa_id_fkey foreign KEY (empresa_id) references empresa (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.notafiscal (
  id integer generated always as identity not null,
  ordemservicoid integer null,
  vendaonlineid integer null,
  tipo character varying not null,
  numero character varying not null,
  serie character varying not null,
  dataemissao timestamp without time zone null default now(),
  xml character varying null,
  protocolo character varying null,
  status character varying not null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  constraint notafiscal_pkey primary key (id),
  constraint fk_nota_fiscal_ordem_servico foreign KEY (ordemservicoid) references ordemservico (id),
  constraint fk_nota_fiscal_venda_online foreign KEY (vendaonlineid) references venda (id)
) TABLESPACE pg_default;

create table public.ordemservico (
  id integer generated always as identity not null,
  clienteid integer not null,
  veiculoid integer null,
  usuariocriadorid uuid not null,
  setorid integer null,
  status public.enum_status_os null default 'AGUARDANDO_CHECKLIST'::enum_status_os,
  statusaprovacao public.enum_status_aprovacao null default 'PENDENTE'::enum_status_aprovacao,
  descricao character varying null,
  dataentrada timestamp without time zone null default now(),
  datasaida timestamp without time zone null,
  orcamentototal numeric not null default '0'::numeric,
  observacoes character varying null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  checklist_modelo_id integer null,
  prioridade public.enum_prioridade_os not null default 'NORMAL'::enum_prioridade_os,
  alvo_tipo public.enum_alvo_reparo not null default 'VEICULO'::enum_alvo_reparo,
  pecaid integer null,
  constraint ordemservico_pkey primary key (id),
  constraint fk_ordem_servico_setor foreign KEY (setorid) references setor (id),
  constraint fk_ordem_servico_usuario foreign KEY (usuariocriadorid) references usuario (id),
  constraint fk_ordem_servico_veiculo foreign KEY (veiculoid) references veiculo (id) on delete CASCADE,
  constraint ordemservico_checklist_modelo_id_fkey foreign KEY (checklist_modelo_id) references checklist_modelo (id),
  constraint ordemservico_pecaid_fkey foreign KEY (pecaid) references peca (id),
  constraint fk_ordem_servico_cliente foreign KEY (clienteid) references cliente (id),
  constraint ordemservico_alvo_consistente check (
    (
      (
        (alvo_tipo = 'VEICULO'::enum_alvo_reparo)
        and (veiculoid is not null)
        and (pecaid is null)
      )
      or (
        (alvo_tipo = 'PECA'::enum_alvo_reparo)
        and (pecaid is not null)
        and (veiculoid is null)
      )
    )
  ) not VALID
) TABLESPACE pg_default;

create index IF not exists idx_os_status on public.ordemservico using btree (status) TABLESPACE pg_default;

create index IF not exists idx_os_cliente on public.ordemservico using btree (clienteid) TABLESPACE pg_default;

create index IF not exists idx_ordemservico_setorid on public.ordemservico using btree (setorid) TABLESPACE pg_default;

create index IF not exists idx_ordemservico_clienteid on public.ordemservico using btree (clienteid) TABLESPACE pg_default;

create trigger ordemservico_status_estorno
after
update OF status on ordemservico for EACH row
execute FUNCTION trg_os_status_estornar ();

create table public.osaprovacao (
  id bigserial not null,
  ordemservicoid integer not null,
  token uuid not null,
  expira_em timestamp with time zone null,
  usado_em timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  origem text null,
  resultado text null,
  aprovador_doc text null,
  aprovador_usuario_id uuid null,
  constraint osaprovacao_pkey primary key (id),
  constraint osaprovacao_token_key unique (token),
  constraint osaprovacao_aprovador_usuario_id_fkey foreign KEY (aprovador_usuario_id) references usuario (id),
  constraint osaprovacao_ordemservicoid_fkey foreign KEY (ordemservicoid) references ordemservico (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists osaprovacao_ordem_idx on public.osaprovacao using btree (ordemservicoid) TABLESPACE pg_default;

create table public.osproduto (
  ordemservicoid integer not null,
  produtoid integer not null,
  quantidade integer null default 1,
  precounitario numeric not null,
  subtotal numeric not null,
  constraint osproduto_pkey primary key (ordemservicoid, produtoid),
  constraint fk_os_produto_ordem foreign KEY (ordemservicoid) references ordemservico (id),
  constraint fk_os_produto_produto foreign KEY (produtoid) references produto (id)
) TABLESPACE pg_default;

create table public.osproduto_baixa (
  ordemservicoid integer not null,
  produtoid integer not null,
  quantidade integer not null default 0,
  constraint osproduto_baixa_pkey primary key (ordemservicoid, produtoid),
  constraint osproduto_baixa_ordemservicoid_fkey foreign KEY (ordemservicoid) references ordemservico (id) on delete CASCADE,
  constraint osproduto_baixa_produtoid_fkey foreign KEY (produtoid) references produto (id)
) TABLESPACE pg_default;

create table public.osservico (
  ordemservicoid integer not null,
  servicoid integer not null,
  quantidade integer null default 1,
  precounitario numeric not null,
  subtotal numeric not null,
  idusuariorealizador uuid null,
  constraint osservico_pkey primary key (ordemservicoid, servicoid),
  constraint fk_os_servico_ordem foreign KEY (ordemservicoid) references ordemservico (id),
  constraint fk_os_servico_servico foreign KEY (servicoid) references servico (id),
  constraint osservico_idusuariorealizador_fkey foreign KEY (idusuariorealizador) references usuario (id) on update CASCADE
) TABLESPACE pg_default;

create table public.pagamento (
  id bigserial not null,
  ordemservicoid integer not null,
  metodo text not null,
  valor numeric not null,
  status text not null default 'CRIADO'::text,
  provider_tx_id text null,
  nsu text null,
  autorizacao text null,
  bandeira text null,
  parcelas integer null default 1,
  comprovante text null,
  criado_em timestamp with time zone null default now(),
  atualizado_em timestamp with time zone null default now(),
  constraint pagamento_pkey primary key (id),
  constraint pagamento_ordemservicoid_fkey foreign KEY (ordemservicoid) references ordemservico (id)
) TABLESPACE pg_default;

create table public.pagamento_config (
  empresa_id integer not null,
  provider_cartao text null default 'stone'::text,
  cartao_merchant_id text null,
  cartao_api_key text null,
  cartao_webhook_url text null,
  cartao_parcelas_max integer null default 1,
  cartao_captura_auto boolean null default true,
  cartao_terminal_ids text[] null default '{}'::text[],
  pix_provider text null default 'stone'::text,
  pix_chave text null,
  pix_client_id text null,
  pix_client_secret text null,
  pix_webhook_url text null,
  pix_expiracao_s integer null default 1800,
  dinheiro_habilitado boolean null default true,
  updated_at timestamp with time zone null default now(),
  constraint pagamento_config_pkey primary key (empresa_id),
  constraint pagamento_config_empresa_id_fkey foreign KEY (empresa_id) references empresa (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.pagamento_evento (
  id bigserial not null,
  pagamentoid bigint not null,
  tipo text not null,
  payload jsonb null,
  criado_em timestamp with time zone null default now(),
  constraint pagamento_evento_pkey primary key (id),
  constraint pagamento_evento_pagamentoid_fkey foreign KEY (pagamentoid) references pagamento (id)
) TABLESPACE pg_default;

create table public.peca (
  id integer generated always as identity not null,
  clienteid integer not null,
  veiculoid integer null,
  titulo text not null,
  descricao text null,
  fabricante text null,
  modelo text null,
  codigo text null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  constraint peca_pkey primary key (id),
  constraint peca_clienteid_fkey foreign KEY (clienteid) references cliente (id),
  constraint peca_veiculoid_fkey foreign KEY (veiculoid) references veiculo (id)
) TABLESPACE pg_default;

create table public.perfil (
  id integer generated always as identity not null,
  nome character varying not null,
  descricao character varying null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  constraint perfil_pkey primary key (id),
  constraint perfil_nome_key unique (nome)
) TABLESPACE pg_default;

create table public.perfilpermissao (
  perfilid integer not null,
  permissaoid integer not null,
  createdat timestamp without time zone null default now(),
  constraint perfilpermissao_pkey primary key (perfilid, permissaoid),
  constraint perfilpermissao_perfil_fkey foreign KEY (perfilid) references perfil (id),
  constraint perfilpermissao_permissao_fkey foreign KEY (permissaoid) references permissao (id)
) TABLESPACE pg_default;

create table public.permissao (
  id integer generated always as identity not null,
  nome character varying not null,
  descricao character varying null,
  constraint permissao_pkey primary key (id),
  constraint permissao_nome_key unique (nome)
) TABLESPACE pg_default;

create table public.produto (
  id integer generated always as identity not null,
  descricao text null,
  precovenda numeric not null,
  estoque integer not null default 0,
  estoqueminimo integer not null default 0,
  ncm text null,
  unidade public.unidade_medida not null default 'UN'::unidade_medida,
  cest text null,
  csosn text null,
  codigobarras text null,
  createdat timestamp with time zone null default now(),
  updatedat timestamp with time zone null default now(),
  referencia text null,
  titulo text not null,
  status_estoque public.estoque_status not null default 'OK'::estoque_status,
  fabricante text null,
  grupo public.grupo_produto null default 'OUTROS'::grupo_produto,
  "imgUrl" text null,
  "exibirPdv" boolean not null default false,
  "tituloMarketplace" text not null default ''::text,
  "descricaoMarketplace" text not null default ''::text,
  "cClassTrib" text null,
  "cstIbs" text null,
  "cstCbs" text null,
  cst text null,
  aliquotaicms numeric null,
  cfop text null,
  cst_pis text null,
  aliquota_pis numeric(5, 2) null,
  cst_cofins text null,
  aliquota_cofins numeric(5, 2) null,
  constraint produto_pkey primary key (id)
) TABLESPACE pg_default;

create trigger trg_fill_titulo_marketplace BEFORE INSERT
or
update OF "tituloMarketplace",
titulo on produto for EACH row
execute FUNCTION fn_fill_titulo_marketplace ();

create trigger trg_set_status_estoque BEFORE INSERT
or
update OF estoque,
estoqueminimo on produto for EACH row
execute FUNCTION fn_set_status_estoque ();

create table public.produtoentrada (
  id bigint generated by default as identity not null,
  quantidade integer not null,
  created_at timestamp with time zone not null default now(),
  produtoid integer not null,
  fornecedorid integer null,
  fiscal boolean not null default false,
  notachave text null,
  constraint produtoentrada_pkey primary key (id),
  constraint produtoentrada_fornecedorid_fkey foreign KEY (fornecedorid) references fornecedor (id),
  constraint produtoentrada_produtoid_fkey foreign KEY (produtoid) references produto (id)
) TABLESPACE pg_default;

create table public.produtogrupo (
  id integer generated always as identity not null,
  nome text not null,
  descricao text null,
  ativo boolean not null default true,
  createdat timestamp without time zone not null default now(),
  updatedat timestamp without time zone not null default now(),
  constraint produtogrupo_pkey primary key (id)
) TABLESPACE pg_default;

create table public.servico (
  id integer generated always as identity not null,
  codigo character varying not null,
  descricao character varying not null,
  precohora numeric not null,
  codigoservicomunicipal character varying not null,
  aliquotaiss numeric null,
  cnae character varying null,
  itemlistaservico character varying not null,
  tiposervicoid integer null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  ativo boolean null default true,
  constraint servico_pkey primary key (id),
  constraint servico_codigo_key unique (codigo),
  constraint fk_servico_tipo_servico foreign KEY (tiposervicoid) references tiposervico (id)
) TABLESPACE pg_default;

create table public.setor (
  id integer generated always as identity not null,
  nome character varying not null,
  descricao character varying null,
  responsavel text null,
  ativo boolean not null default true,
  constraint setor_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tiposervico (
  id integer generated always as identity not null,
  nome character varying not null,
  descricao character varying null,
  categoriaid integer not null,
  constraint tiposervico_pkey primary key (id),
  constraint fk_tipo_servico_categoria foreign KEY (categoriaid) references categoriaservico (id)
) TABLESPACE pg_default;

create table public.transacao (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  descricao text not null,
  valor numeric(14, 2) not null,
  data timestamp with time zone not null,
  metodopagamento public.metodo_pagamento not null,
  categoria public.categoria_transacao not null,
  tipo public.tipos_transacao not null,
  cliente_id integer null,
  banco_id bigint not null,
  nomepagador text not null,
  cpfcnpjpagador text not null,
  ordemservicoid integer null,
  "valorLiquido" numeric null,
  vendaid integer null,
  pendente boolean not null default false,
  constraint transacao_pkey primary key (id),
  constraint transacao_banco_id_fkey foreign KEY (banco_id) references bancoconta (id) on update RESTRICT,
  constraint transacao_cliente_id_fkey foreign KEY (cliente_id) references cliente (id) on update CASCADE,
  constraint transacao_ordemservicoid_fkey foreign KEY (ordemservicoid) references ordemservico (id) on delete set null,
  constraint transacao_vendaid_fkey foreign KEY (vendaid) references venda (id)
) TABLESPACE pg_default;

create index IF not exists idx_transacao_ordemservicoid on public.transacao using btree (ordemservicoid) TABLESPACE pg_default;

create table public.unidademedida (
  id integer generated always as identity not null,
  sigla character varying not null,
  descricao text null,
  ativo boolean not null default true,
  createdat timestamp without time zone not null default now(),
  updatedat timestamp without time zone not null default now(),
  constraint unidademedida_pkey primary key (id),
  constraint unidademedida_sigla_key unique (sigla)
) TABLESPACE pg_default;

create table public.usuario (
  id uuid not null default gen_random_uuid (),
  email character varying not null,
  nome character varying not null,
  setorid integer null,
  perfilid integer null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  ativo boolean not null default true,
  constraint usuario_pkey primary key (id),
  constraint usuario_email_key unique (email),
  constraint usuario_auth_fkey foreign KEY (id) references auth.users (id) on delete CASCADE,
  constraint usuario_perfilid_fkey foreign KEY (perfilid) references perfil (id),
  constraint usuario_setorid_fkey foreign KEY (setorid) references setor (id)
) TABLESPACE pg_default;

create index IF not exists idx_usuario_email on public.usuario using btree (email) TABLESPACE pg_default;

create table public.veiculo (
  id integer generated always as identity not null,
  clienteid integer not null,
  placa character varying not null,
  modelo character varying not null,
  marca character varying not null,
  ano integer null,
  cor character varying null,
  kmatual integer null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  constraint veiculo_pkey primary key (id),
  constraint veiculo_placa_key unique (placa),
  constraint fk_veiculo_cliente foreign KEY (clienteid) references cliente (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.venda (
  id integer generated always as identity not null,
  clienteid integer not null,
  status public.enum_status_venda not null,
  valortotal numeric not null,
  datavenda timestamp with time zone null,
  createdat timestamp with time zone null,
  updatedat timestamp with time zone null,
  usuariocriadorid uuid null,
  desconto_tipo public.enum_tipo_desconto_venda null,
  desconto_valor numeric null,
  sub_total numeric not null,
  constraint vendaonline_pkey primary key (id),
  constraint fk_venda_online_cliente foreign KEY (clienteid) references cliente (id),
  constraint vendaonline_usuariocriadorid_fkey foreign KEY (usuariocriadorid) references usuario (id)
) TABLESPACE pg_default;

create table public.vendaproduto (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  venda_id integer not null,
  produtoid integer not null,
  sub_total numeric not null,
  valor_total numeric not null,
  valor_desconto numeric null,
  tipo_desconto public.enum_tipo_desconto_venda null,
  quantidade numeric not null,
  constraint vendaproduto_pkey primary key (id),
  constraint vendaproduto_produtoid_fkey foreign KEY (produtoid) references produto (id),
  constraint vendaproduto_vendaId_fkey foreign KEY (venda_id) references venda (id)
) TABLESPACE pg_default;

