--
-- PostgreSQL database dump
--

\restrict ZnPdZw9XPfvLBbq0mNjMF0M0dfDuTRXznYjmmNjHtaHApeqrvtJNqUkszNZIvFu

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.1

-- Started on 2025-12-09 18:30:28

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 425 (class 1259 OID 50364)
-- Name: bancoconta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bancoconta (
    id bigint NOT NULL,
    titulo text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    valorinicial real NOT NULL,
    agencia text,
    contanumero text,
    tipo public.banco_tipo DEFAULT 'CORRENTE'::public.banco_tipo NOT NULL,
    proprietario text,
    empresa_id integer,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    ativo boolean DEFAULT true
);


ALTER TABLE public.bancoconta OWNER TO postgres;

--
-- TOC entry 426 (class 1259 OID 50367)
-- Name: banco_conta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bancoconta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.banco_conta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 384 (class 1259 OID 17374)
-- Name: categoriaservico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categoriaservico (
    id integer NOT NULL,
    nome character varying NOT NULL,
    descricao character varying
);


ALTER TABLE public.categoriaservico OWNER TO postgres;

--
-- TOC entry 383 (class 1259 OID 17373)
-- Name: categoriaservico_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categoriaservico ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.categoriaservico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 453 (class 1259 OID 93731)
-- Name: categoriatransacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categoriatransacao (
    id integer NOT NULL,
    nome text NOT NULL,
    descricao text,
    ativo boolean DEFAULT true NOT NULL,
    createdat timestamp without time zone DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now()
);


ALTER TABLE public.categoriatransacao OWNER TO postgres;

--
-- TOC entry 452 (class 1259 OID 93730)
-- Name: categoriatransacao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categoriatransacao ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.categoriatransacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 410 (class 1259 OID 17582)
-- Name: checklist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.checklist (
    id integer NOT NULL,
    ordemservicoid integer NOT NULL,
    item character varying NOT NULL,
    status public.enum_status_checklist DEFAULT 'OK'::public.enum_status_checklist NOT NULL,
    observacao character varying,
    createdat timestamp without time zone DEFAULT now()
);


ALTER TABLE public.checklist OWNER TO postgres;

--
-- TOC entry 409 (class 1259 OID 17581)
-- Name: checklist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.checklist ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.checklist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 422 (class 1259 OID 26483)
-- Name: checklist_modelo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.checklist_modelo (
    id integer NOT NULL,
    nome character varying NOT NULL,
    descricao character varying,
    categoria character varying,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp without time zone DEFAULT now() NOT NULL,
    atualizado_em timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.checklist_modelo OWNER TO postgres;

--
-- TOC entry 421 (class 1259 OID 26482)
-- Name: checklist_modelo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.checklist_modelo ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.checklist_modelo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 424 (class 1259 OID 26496)
-- Name: checklist_modelo_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.checklist_modelo_item (
    id integer NOT NULL,
    modelo_id integer NOT NULL,
    titulo character varying NOT NULL,
    descricao character varying,
    categoria character varying,
    obrigatorio boolean DEFAULT false NOT NULL,
    ordem integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.checklist_modelo_item OWNER TO postgres;

--
-- TOC entry 423 (class 1259 OID 26495)
-- Name: checklist_modelo_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.checklist_modelo_item ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.checklist_modelo_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 393 (class 1259 OID 17435)
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    id integer NOT NULL,
    tipopessoa public.enum_tipopessoa NOT NULL,
    cpfcnpj character varying NOT NULL,
    nomerazaosocial character varying NOT NULL,
    email character varying NOT NULL,
    telefone character varying NOT NULL,
    endereco character varying,
    cidade character varying NOT NULL,
    estado character varying NOT NULL,
    cep character varying,
    inscricaoestadual character varying,
    inscricaomunicipal character varying,
    codigomunicipio character varying,
    createdat timestamp without time zone DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now(),
    status public.enum_status_cliente DEFAULT 'ATIVO'::public.enum_status_cliente,
    endereconumero text,
    enderecocomplemento text,
    bairro text
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- TOC entry 392 (class 1259 OID 17434)
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cliente ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 395 (class 1259 OID 17447)
-- Name: empresa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empresa (
    id integer NOT NULL,
    cnpj character varying NOT NULL,
    razaosocial character varying NOT NULL,
    nomefantasia character varying,
    inscricaoestadual character varying,
    inscricaomunicipal character varying,
    endereco character varying NOT NULL,
    codigomunicipio character varying NOT NULL,
    regimetributario character varying NOT NULL,
    certificadocaminho character varying,
    cschomologacao character varying,
    cscproducao character varying,
    ambiente character varying DEFAULT 'HOMOLOGACAO'::character varying,
    createdat timestamp without time zone DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now(),
    bairro character varying,
    numero character varying,
    complemento character varying,
    cep character varying,
    uf character varying(2),
    codigopais character varying DEFAULT '1058'::character varying,
    nomepais character varying DEFAULT 'BRASIL'::character varying,
    telefone character varying,
    cnae character varying,
    inscricaoestadualst character varying,
    certificadosenha character varying,
    CONSTRAINT empresa_ambiente_check CHECK (((ambiente)::text = ANY ((ARRAY['HOMOLOGACAO'::character varying, 'PRODUCAO'::character varying])::text[]))),
    CONSTRAINT empresa_regimetributario_check CHECK (((regimetributario)::text = ANY ((ARRAY['1'::character varying, '2'::character varying, '3'::character varying])::text[])))
);


ALTER TABLE public.empresa OWNER TO postgres;

--
-- TOC entry 394 (class 1259 OID 17446)
-- Name: empresa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empresa ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.empresa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 397 (class 1259 OID 17460)
-- Name: fornecedor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fornecedor (
    id integer NOT NULL,
    cpfcnpj character varying NOT NULL,
    nomerazaosocial text NOT NULL,
    nomefantasia character varying,
    endereco character varying,
    cidade character varying,
    estado character varying,
    cep character varying,
    contato character varying,
    createdat timestamp without time zone DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now(),
    endereconumero text,
    enderecocomplemento text,
    bairro text,
    ativo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.fornecedor OWNER TO postgres;

--
-- TOC entry 396 (class 1259 OID 17459)
-- Name: fornecedor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fornecedor ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.fornecedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 454 (class 1259 OID 98379)
-- Name: fornecedorprodutos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fornecedorprodutos (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    fornecedorid integer NOT NULL,
    produtoid integer NOT NULL,
    codigofornecedor text NOT NULL,
    ultimovalordecompra numeric
);


ALTER TABLE public.fornecedorprodutos OWNER TO postgres;

--
-- TOC entry 455 (class 1259 OID 98382)
-- Name: fornecedorprodutos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fornecedorprodutos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fornecedorprodutos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 412 (class 1259 OID 17596)
-- Name: imagemvistoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.imagemvistoria (
    id integer NOT NULL,
    checklistid integer NOT NULL,
    url character varying NOT NULL,
    descricao character varying,
    createdat timestamp without time zone DEFAULT now()
);


ALTER TABLE public.imagemvistoria OWNER TO postgres;

--
-- TOC entry 411 (class 1259 OID 17595)
-- Name: imagemvistoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.imagemvistoria ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.imagemvistoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 460 (class 1259 OID 102826)
-- Name: nfe; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nfe (
    id bigint NOT NULL,
    modelo public.enum_modelo_nfe DEFAULT 'NFE'::public.enum_modelo_nfe NOT NULL,
    serie integer NOT NULL,
    numero integer NOT NULL,
    chave_acesso character(44) NOT NULL,
    ambiente public.enum_ambiente_nfe DEFAULT 'HOMOLOGACAO'::public.enum_ambiente_nfe NOT NULL,
    status public.enum_status_nfe DEFAULT 'RASCUNHO'::public.enum_status_nfe NOT NULL,
    ordemservicoid integer,
    vendaid integer,
    clienteid integer NOT NULL,
    dataemissao timestamp with time zone NOT NULL,
    dataautorizacao timestamp with time zone,
    protocolo text,
    total_produtos numeric(14,2) DEFAULT 0 NOT NULL,
    total_servicos numeric(14,2) DEFAULT 0 NOT NULL,
    total_nfe numeric(14,2) DEFAULT 0 NOT NULL,
    xml_assinado text,
    xml_autorizado text,
    justificativacancelamento text,
    createdat timestamp with time zone DEFAULT now() NOT NULL,
    updatedat timestamp with time zone DEFAULT now() NOT NULL,
    empresaid integer NOT NULL
);


ALTER TABLE public.nfe OWNER TO postgres;

--
-- TOC entry 468 (class 1259 OID 109861)
-- Name: nfe_config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nfe_config (
    id bigint NOT NULL,
    empresaid bigint NOT NULL,
    modelo public.enum_modelo_nfe DEFAULT 'NFE'::public.enum_modelo_nfe NOT NULL,
    serie integer DEFAULT 1 NOT NULL,
    ultimo_numero integer DEFAULT 0 NOT NULL,
    ambiente public.enum_ambiente_nfe DEFAULT 'HOMOLOGACAO'::public.enum_ambiente_nfe NOT NULL,
    tp_emis smallint DEFAULT 1 NOT NULL,
    versao_layout character varying(5) DEFAULT '4.00'::character varying NOT NULL,
    tipo_impressao_danfe smallint DEFAULT 1 NOT NULL,
    permitir_homologacao boolean DEFAULT true NOT NULL,
    permitir_producao boolean DEFAULT true NOT NULL,
    createdat timestamp with time zone DEFAULT now() NOT NULL,
    updatedat timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.nfe_config OWNER TO postgres;

--
-- TOC entry 467 (class 1259 OID 109860)
-- Name: nfe_config_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.nfe_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.nfe_config_id_seq OWNER TO postgres;

--
-- TOC entry 4348 (class 0 OID 0)
-- Dependencies: 467
-- Name: nfe_config_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.nfe_config_id_seq OWNED BY public.nfe_config.id;


--
-- TOC entry 459 (class 1259 OID 102825)
-- Name: nfe_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.nfe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.nfe_id_seq OWNER TO postgres;

--
-- TOC entry 4350 (class 0 OID 0)
-- Dependencies: 459
-- Name: nfe_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.nfe_id_seq OWNED BY public.nfe.id;


--
-- TOC entry 462 (class 1259 OID 102864)
-- Name: nfe_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nfe_item (
    id bigint NOT NULL,
    nfe_id bigint NOT NULL,
    n_item integer NOT NULL,
    produtoid integer,
    descricao text NOT NULL,
    ncm text,
    cfop text NOT NULL,
    csosn text,
    cest text,
    unidade public.unidade_medida NOT NULL,
    quantidade numeric(14,4) NOT NULL,
    valor_unitario numeric(14,10) NOT NULL,
    valor_total numeric(14,2) NOT NULL,
    valor_desconto numeric(14,2),
    aliquotaicms numeric(5,2),
    valor_bc_icms numeric(14,2),
    valor_icms numeric(14,2),
    cst_pis text,
    aliquota_pis numeric(5,2),
    valor_pis numeric(14,2),
    cst_cofins text,
    aliquota_cofins numeric(5,2),
    valor_cofins numeric(14,2),
    createdat timestamp with time zone DEFAULT now() NOT NULL,
    updatedat timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.nfe_item OWNER TO postgres;

--
-- TOC entry 461 (class 1259 OID 102863)
-- Name: nfe_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.nfe_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.nfe_item_id_seq OWNER TO postgres;

--
-- TOC entry 4353 (class 0 OID 0)
-- Dependencies: 461
-- Name: nfe_item_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.nfe_item_id_seq OWNED BY public.nfe_item.id;


--
-- TOC entry 438 (class 1259 OID 63543)
-- Name: nfse_config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nfse_config (
    empresa_id integer NOT NULL,
    provedor text,
    inscricao_municipal text,
    serie_rps text,
    usuario text,
    senha text,
    token text,
    certificado_a1_base64 text,
    senha_certificado text,
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.nfse_config OWNER TO postgres;

--
-- TOC entry 418 (class 1259 OID 17709)
-- Name: notafiscal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notafiscal (
    id integer NOT NULL,
    ordemservicoid integer,
    vendaonlineid integer,
    tipo character varying NOT NULL,
    numero character varying NOT NULL,
    serie character varying NOT NULL,
    dataemissao timestamp without time zone DEFAULT now(),
    xml character varying,
    protocolo character varying,
    status character varying NOT NULL,
    createdat timestamp without time zone DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now()
);


ALTER TABLE public.notafiscal OWNER TO postgres;

--
-- TOC entry 417 (class 1259 OID 17708)
-- Name: notafiscal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notafiscal ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.notafiscal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 408 (class 1259 OID 17549)
-- Name: ordemservico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ordemservico (
    id integer NOT NULL,
    clienteid integer NOT NULL,
    veiculoid integer,
    usuariocriadorid uuid NOT NULL,
    setorid integer,
    status public.enum_status_os DEFAULT 'AGUARDANDO_CHECKLIST'::public.enum_status_os,
    statusaprovacao public.enum_status_aprovacao DEFAULT 'PENDENTE'::public.enum_status_aprovacao,
    descricao character varying,
    dataentrada timestamp without time zone DEFAULT now(),
    datasaida timestamp without time zone,
    orcamentototal numeric DEFAULT '0'::numeric NOT NULL,
    observacoes character varying,
    createdat timestamp without time zone DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now(),
    checklist_modelo_id integer,
    prioridade public.enum_prioridade_os DEFAULT 'NORMAL'::public.enum_prioridade_os NOT NULL,
    alvo_tipo public.enum_alvo_reparo DEFAULT 'VEICULO'::public.enum_alvo_reparo NOT NULL,
    pecaid integer
);


ALTER TABLE public.ordemservico OWNER TO postgres;

--
-- TOC entry 407 (class 1259 OID 17548)
-- Name: ordemservico_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ordemservico ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.ordemservico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 432 (class 1259 OID 61167)
-- Name: osaprovacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.osaprovacao (
    id bigint NOT NULL,
    ordemservicoid integer NOT NULL,
    token uuid NOT NULL,
    expira_em timestamp with time zone,
    usado_em timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    origem text,
    resultado text,
    aprovador_doc text,
    aprovador_usuario_id uuid
);


ALTER TABLE public.osaprovacao OWNER TO postgres;

--
-- TOC entry 431 (class 1259 OID 61166)
-- Name: osaprovacao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.osaprovacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.osaprovacao_id_seq OWNER TO postgres;

--
-- TOC entry 4361 (class 0 OID 0)
-- Dependencies: 431
-- Name: osaprovacao_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.osaprovacao_id_seq OWNED BY public.osaprovacao.id;


--
-- TOC entry 415 (class 1259 OID 17625)
-- Name: osproduto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.osproduto (
    ordemservicoid integer NOT NULL,
    produtoid integer NOT NULL,
    quantidade integer DEFAULT 1,
    precounitario numeric NOT NULL,
    subtotal numeric NOT NULL
);


ALTER TABLE public.osproduto OWNER TO postgres;

--
-- TOC entry 441 (class 1259 OID 77608)
-- Name: osproduto_baixa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.osproduto_baixa (
    ordemservicoid integer NOT NULL,
    produtoid integer NOT NULL,
    quantidade integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.osproduto_baixa OWNER TO postgres;

--
-- TOC entry 416 (class 1259 OID 17643)
-- Name: osservico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.osservico (
    ordemservicoid integer NOT NULL,
    servicoid integer NOT NULL,
    quantidade integer DEFAULT 1,
    precounitario numeric NOT NULL,
    subtotal numeric NOT NULL,
    idusuariorealizador uuid
);


ALTER TABLE public.osservico OWNER TO postgres;

--
-- TOC entry 434 (class 1259 OID 63469)
-- Name: pagamento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pagamento (
    id bigint NOT NULL,
    ordemservicoid integer NOT NULL,
    metodo text NOT NULL,
    valor numeric NOT NULL,
    status text DEFAULT 'CRIADO'::text NOT NULL,
    provider_tx_id text,
    nsu text,
    autorizacao text,
    bandeira text,
    parcelas integer DEFAULT 1,
    comprovante text,
    criado_em timestamp with time zone DEFAULT now(),
    atualizado_em timestamp with time zone DEFAULT now()
);


ALTER TABLE public.pagamento OWNER TO postgres;

--
-- TOC entry 437 (class 1259 OID 63523)
-- Name: pagamento_config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pagamento_config (
    empresa_id integer NOT NULL,
    provider_cartao text DEFAULT 'stone'::text,
    cartao_merchant_id text,
    cartao_api_key text,
    cartao_webhook_url text,
    cartao_parcelas_max integer DEFAULT 1,
    cartao_captura_auto boolean DEFAULT true,
    cartao_terminal_ids text[] DEFAULT '{}'::text[],
    pix_provider text DEFAULT 'stone'::text,
    pix_chave text,
    pix_client_id text,
    pix_client_secret text,
    pix_webhook_url text,
    pix_expiracao_s integer DEFAULT 1800,
    dinheiro_habilitado boolean DEFAULT true,
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.pagamento_config OWNER TO postgres;

--
-- TOC entry 436 (class 1259 OID 63487)
-- Name: pagamento_evento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pagamento_evento (
    id bigint NOT NULL,
    pagamentoid bigint NOT NULL,
    tipo text NOT NULL,
    payload jsonb,
    criado_em timestamp with time zone DEFAULT now()
);


ALTER TABLE public.pagamento_evento OWNER TO postgres;

--
-- TOC entry 435 (class 1259 OID 63486)
-- Name: pagamento_evento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.pagamento_evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.pagamento_evento_id_seq OWNER TO postgres;

--
-- TOC entry 4369 (class 0 OID 0)
-- Dependencies: 435
-- Name: pagamento_evento_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.pagamento_evento_id_seq OWNED BY public.pagamento_evento.id;


--
-- TOC entry 433 (class 1259 OID 63468)
-- Name: pagamento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.pagamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.pagamento_id_seq OWNER TO postgres;

--
-- TOC entry 4371 (class 0 OID 0)
-- Dependencies: 433
-- Name: pagamento_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.pagamento_id_seq OWNED BY public.pagamento.id;


--
-- TOC entry 440 (class 1259 OID 69372)
-- Name: peca; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.peca (
    id integer NOT NULL,
    clienteid integer NOT NULL,
    veiculoid integer,
    titulo text NOT NULL,
    descricao text,
    fabricante text,
    modelo text,
    codigo text,
    createdat timestamp without time zone DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now()
);


ALTER TABLE public.peca OWNER TO postgres;

--
-- TOC entry 439 (class 1259 OID 69371)
-- Name: peca_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.peca ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.peca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 388 (class 1259 OID 17392)
-- Name: perfil; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.perfil (
    id integer NOT NULL,
    nome character varying NOT NULL,
    descricao character varying,
    createdat timestamp without time zone DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now()
);


ALTER TABLE public.perfil OWNER TO postgres;

--
-- TOC entry 387 (class 1259 OID 17391)
-- Name: perfil_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.perfil ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.perfil_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 404 (class 1259 OID 17515)
-- Name: perfilpermissao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.perfilpermissao (
    perfilid integer NOT NULL,
    permissaoid integer NOT NULL,
    createdat timestamp without time zone DEFAULT now()
);


ALTER TABLE public.perfilpermissao OWNER TO postgres;

--
-- TOC entry 386 (class 1259 OID 17382)
-- Name: permissao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permissao (
    id integer NOT NULL,
    nome character varying NOT NULL,
    descricao character varying
);


ALTER TABLE public.permissao OWNER TO postgres;

--
-- TOC entry 385 (class 1259 OID 17381)
-- Name: permissao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permissao ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.permissao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 403 (class 1259 OID 17502)
-- Name: produto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produto (
    id integer NOT NULL,
    descricao text,
    precovenda numeric NOT NULL,
    estoque integer DEFAULT 0 NOT NULL,
    estoqueminimo integer DEFAULT 0 NOT NULL,
    ncm text,
    cfop text,
    unidade public.unidade_medida DEFAULT 'UN'::public.unidade_medida NOT NULL,
    cest text,
    csosn text,
    aliquotaicms numeric,
    codigobarras text,
    createdat timestamp with time zone DEFAULT now(),
    updatedat timestamp with time zone DEFAULT now(),
    referencia text,
    titulo text NOT NULL,
    status_estoque public.estoque_status DEFAULT 'OK'::public.estoque_status NOT NULL,
    fabricante text,
    grupo public.grupo_produto DEFAULT 'OUTROS'::public.grupo_produto,
    "imgUrl" text,
    "exibirPdv" boolean DEFAULT false NOT NULL,
    "tituloMarketplace" text DEFAULT ''::text NOT NULL,
    "descricaoMarketplace" text DEFAULT ''::text NOT NULL,
    "cClassTrib" text,
    "cstIbs" text,
    "cstCbs" text
);


ALTER TABLE public.produto OWNER TO postgres;

--
-- TOC entry 402 (class 1259 OID 17501)
-- Name: produto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produto ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.produto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 446 (class 1259 OID 87986)
-- Name: produtoentrada; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produtoentrada (
    id bigint NOT NULL,
    quantidade integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    produtoid integer NOT NULL,
    fornecedorid integer,
    fiscal boolean DEFAULT false NOT NULL,
    notachave text
);


ALTER TABLE public.produtoentrada OWNER TO postgres;

--
-- TOC entry 447 (class 1259 OID 87989)
-- Name: produtoentrada_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produtoentrada ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produtoentrada_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 449 (class 1259 OID 93623)
-- Name: produtogrupo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produtogrupo (
    id integer NOT NULL,
    nome text NOT NULL,
    descricao text,
    ativo boolean DEFAULT true NOT NULL,
    createdat timestamp without time zone DEFAULT now() NOT NULL,
    updatedat timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.produtogrupo OWNER TO postgres;

--
-- TOC entry 448 (class 1259 OID 93622)
-- Name: produtogrupo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produtogrupo ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.produtogrupo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 401 (class 1259 OID 17485)
-- Name: servico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.servico (
    id integer NOT NULL,
    codigo character varying NOT NULL,
    descricao character varying NOT NULL,
    precohora numeric NOT NULL,
    codigoservicomunicipal character varying NOT NULL,
    aliquotaiss numeric,
    cnae character varying,
    itemlistaservico character varying NOT NULL,
    tiposervicoid integer,
    createdat timestamp without time zone DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now(),
    ativo boolean DEFAULT true
);


ALTER TABLE public.servico OWNER TO postgres;

--
-- TOC entry 400 (class 1259 OID 17484)
-- Name: servico_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.servico ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.servico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 390 (class 1259 OID 17404)
-- Name: setor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.setor (
    id integer NOT NULL,
    nome character varying NOT NULL,
    descricao character varying,
    responsavel text,
    ativo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.setor OWNER TO postgres;

--
-- TOC entry 389 (class 1259 OID 17403)
-- Name: setor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.setor ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.setor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 399 (class 1259 OID 17472)
-- Name: tiposervico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tiposervico (
    id integer NOT NULL,
    nome character varying NOT NULL,
    descricao character varying,
    categoriaid integer NOT NULL
);


ALTER TABLE public.tiposervico OWNER TO postgres;

--
-- TOC entry 398 (class 1259 OID 17471)
-- Name: tiposervico_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tiposervico ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tiposervico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 427 (class 1259 OID 50465)
-- Name: transacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transacao (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    descricao text NOT NULL,
    valor numeric(14,2) NOT NULL,
    data timestamp with time zone NOT NULL,
    metodopagamento public.metodo_pagamento NOT NULL,
    categoria public.categoria_transacao NOT NULL,
    tipo public.tipos_transacao NOT NULL,
    cliente_id integer,
    banco_id bigint NOT NULL,
    nomepagador text NOT NULL,
    cpfcnpjpagador text NOT NULL,
    ordemservicoid integer,
    "valorLiquido" numeric,
    vendaid integer,
    pendente boolean DEFAULT false NOT NULL
);


ALTER TABLE public.transacao OWNER TO postgres;

--
-- TOC entry 428 (class 1259 OID 50468)
-- Name: transacao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 451 (class 1259 OID 93675)
-- Name: unidademedida; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.unidademedida (
    id integer NOT NULL,
    sigla character varying NOT NULL,
    descricao text,
    ativo boolean DEFAULT true NOT NULL,
    createdat timestamp without time zone DEFAULT now() NOT NULL,
    updatedat timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.unidademedida OWNER TO postgres;

--
-- TOC entry 450 (class 1259 OID 93674)
-- Name: unidademedida_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.unidademedida ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.unidademedida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 391 (class 1259 OID 17411)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying NOT NULL,
    nome character varying NOT NULL,
    setorid integer,
    perfilid integer,
    createdat timestamp without time zone DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now(),
    ativo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 406 (class 1259 OID 17532)
-- Name: veiculo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.veiculo (
    id integer NOT NULL,
    clienteid integer NOT NULL,
    placa character varying NOT NULL,
    modelo character varying NOT NULL,
    marca character varying NOT NULL,
    ano integer,
    cor character varying,
    kmatual integer,
    createdat timestamp without time zone DEFAULT now(),
    updatedat timestamp without time zone DEFAULT now()
);


ALTER TABLE public.veiculo OWNER TO postgres;

--
-- TOC entry 405 (class 1259 OID 17531)
-- Name: veiculo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.veiculo ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.veiculo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 414 (class 1259 OID 17610)
-- Name: venda; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.venda (
    id integer NOT NULL,
    clienteid integer NOT NULL,
    status public.enum_status_venda NOT NULL,
    valortotal numeric NOT NULL,
    datavenda timestamp with time zone,
    createdat timestamp with time zone,
    updatedat timestamp with time zone,
    usuariocriadorid uuid,
    desconto_tipo public.enum_tipo_desconto_venda,
    desconto_valor numeric,
    sub_total numeric NOT NULL
);


ALTER TABLE public.venda OWNER TO postgres;

--
-- TOC entry 413 (class 1259 OID 17609)
-- Name: vendaonline_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.venda ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.vendaonline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 442 (class 1259 OID 81317)
-- Name: vendaproduto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vendaproduto (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    venda_id integer NOT NULL,
    produtoid integer NOT NULL,
    sub_total numeric NOT NULL,
    valor_total numeric NOT NULL,
    valor_desconto numeric,
    tipo_desconto public.enum_tipo_desconto_venda,
    quantidade numeric NOT NULL
);


ALTER TABLE public.vendaproduto OWNER TO postgres;

--
-- TOC entry 443 (class 1259 OID 81320)
-- Name: vendaproduto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vendaproduto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendaproduto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3954 (class 2604 OID 102829)
-- Name: nfe id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe ALTER COLUMN id SET DEFAULT nextval('public.nfe_id_seq'::regclass);


--
-- TOC entry 3966 (class 2604 OID 109864)
-- Name: nfe_config id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe_config ALTER COLUMN id SET DEFAULT nextval('public.nfe_config_id_seq'::regclass);


--
-- TOC entry 3963 (class 2604 OID 102867)
-- Name: nfe_item id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe_item ALTER COLUMN id SET DEFAULT nextval('public.nfe_item_id_seq'::regclass);


--
-- TOC entry 3919 (class 2604 OID 61170)
-- Name: osaprovacao id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osaprovacao ALTER COLUMN id SET DEFAULT nextval('public.osaprovacao_id_seq'::regclass);


--
-- TOC entry 3921 (class 2604 OID 63472)
-- Name: pagamento id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagamento ALTER COLUMN id SET DEFAULT nextval('public.pagamento_id_seq'::regclass);


--
-- TOC entry 3926 (class 2604 OID 63490)
-- Name: pagamento_evento id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagamento_evento ALTER COLUMN id SET DEFAULT nextval('public.pagamento_evento_id_seq'::regclass);


--
-- TOC entry 4055 (class 2606 OID 50374)
-- Name: bancoconta banco_conta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bancoconta
    ADD CONSTRAINT banco_conta_pkey PRIMARY KEY (id);


--
-- TOC entry 4087 (class 2606 OID 93742)
-- Name: categoriatransacao categoria_transacao_nome_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoriatransacao
    ADD CONSTRAINT categoria_transacao_nome_key UNIQUE (nome);


--
-- TOC entry 3982 (class 2606 OID 17380)
-- Name: categoriaservico categoriaservico_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoriaservico
    ADD CONSTRAINT categoriaservico_pkey PRIMARY KEY (id);


--
-- TOC entry 4089 (class 2606 OID 93740)
-- Name: categoriatransacao categoriatransacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoriatransacao
    ADD CONSTRAINT categoriatransacao_pkey PRIMARY KEY (id);


--
-- TOC entry 4052 (class 2606 OID 26504)
-- Name: checklist_modelo_item checklist_modelo_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checklist_modelo_item
    ADD CONSTRAINT checklist_modelo_item_pkey PRIMARY KEY (id);


--
-- TOC entry 4048 (class 2606 OID 26494)
-- Name: checklist_modelo checklist_modelo_nome_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checklist_modelo
    ADD CONSTRAINT checklist_modelo_nome_key UNIQUE (nome);


--
-- TOC entry 4050 (class 2606 OID 26492)
-- Name: checklist_modelo checklist_modelo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checklist_modelo
    ADD CONSTRAINT checklist_modelo_pkey PRIMARY KEY (id);


--
-- TOC entry 4036 (class 2606 OID 17589)
-- Name: checklist checklist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checklist
    ADD CONSTRAINT checklist_pkey PRIMARY KEY (id);


--
-- TOC entry 3999 (class 2606 OID 17445)
-- Name: cliente cliente_cpfcnpj_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_cpfcnpj_key UNIQUE (cpfcnpj);


--
-- TOC entry 4001 (class 2606 OID 35958)
-- Name: cliente cliente_nomerazaosocial_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_nomerazaosocial_key UNIQUE (nomerazaosocial);


--
-- TOC entry 4003 (class 2606 OID 17443)
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- TOC entry 4005 (class 2606 OID 35962)
-- Name: cliente cliente_telefone_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_telefone_key UNIQUE (telefone);


--
-- TOC entry 4008 (class 2606 OID 17458)
-- Name: empresa empresa_cnpj_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_cnpj_key UNIQUE (cnpj);


--
-- TOC entry 4010 (class 2606 OID 17456)
-- Name: empresa empresa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_pkey PRIMARY KEY (id);


--
-- TOC entry 4012 (class 2606 OID 17470)
-- Name: fornecedor fornecedor_cnpj_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fornecedor
    ADD CONSTRAINT fornecedor_cnpj_key UNIQUE (cpfcnpj);


--
-- TOC entry 4014 (class 2606 OID 17468)
-- Name: fornecedor fornecedor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fornecedor
    ADD CONSTRAINT fornecedor_pkey PRIMARY KEY (id);


--
-- TOC entry 4091 (class 2606 OID 98390)
-- Name: fornecedorprodutos fornecedorprodutos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fornecedorprodutos
    ADD CONSTRAINT fornecedorprodutos_pkey PRIMARY KEY (id);


--
-- TOC entry 4038 (class 2606 OID 17603)
-- Name: imagemvistoria imagemvistoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imagemvistoria
    ADD CONSTRAINT imagemvistoria_pkey PRIMARY KEY (id);


--
-- TOC entry 4097 (class 2606 OID 102843)
-- Name: nfe nfe_chave_acesso_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe
    ADD CONSTRAINT nfe_chave_acesso_key UNIQUE (chave_acesso);


--
-- TOC entry 4105 (class 2606 OID 109879)
-- Name: nfe_config nfe_config_empresaid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe_config
    ADD CONSTRAINT nfe_config_empresaid_key UNIQUE (empresaid);


--
-- TOC entry 4107 (class 2606 OID 109877)
-- Name: nfe_config nfe_config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe_config
    ADD CONSTRAINT nfe_config_pkey PRIMARY KEY (id);


--
-- TOC entry 4103 (class 2606 OID 102873)
-- Name: nfe_item nfe_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe_item
    ADD CONSTRAINT nfe_item_pkey PRIMARY KEY (id);


--
-- TOC entry 4099 (class 2606 OID 102841)
-- Name: nfe nfe_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe
    ADD CONSTRAINT nfe_pkey PRIMARY KEY (id);


--
-- TOC entry 4071 (class 2606 OID 63550)
-- Name: nfse_config nfse_config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfse_config
    ADD CONSTRAINT nfse_config_pkey PRIMARY KEY (empresa_id);


--
-- TOC entry 4046 (class 2606 OID 17718)
-- Name: notafiscal notafiscal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notafiscal
    ADD CONSTRAINT notafiscal_pkey PRIMARY KEY (id);


--
-- TOC entry 3980 (class 2606 OID 69397)
-- Name: ordemservico ordemservico_alvo_consistente; Type: CHECK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE public.ordemservico
    ADD CONSTRAINT ordemservico_alvo_consistente CHECK ((((alvo_tipo = 'VEICULO'::public.enum_alvo_reparo) AND (veiculoid IS NOT NULL) AND (pecaid IS NULL)) OR ((alvo_tipo = 'PECA'::public.enum_alvo_reparo) AND (pecaid IS NOT NULL) AND (veiculoid IS NULL)))) NOT VALID;


--
-- TOC entry 4034 (class 2606 OID 17560)
-- Name: ordemservico ordemservico_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ordemservico
    ADD CONSTRAINT ordemservico_pkey PRIMARY KEY (id);


--
-- TOC entry 4061 (class 2606 OID 61173)
-- Name: osaprovacao osaprovacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osaprovacao
    ADD CONSTRAINT osaprovacao_pkey PRIMARY KEY (id);


--
-- TOC entry 4063 (class 2606 OID 61175)
-- Name: osaprovacao osaprovacao_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osaprovacao
    ADD CONSTRAINT osaprovacao_token_key UNIQUE (token);


--
-- TOC entry 4075 (class 2606 OID 77613)
-- Name: osproduto_baixa osproduto_baixa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osproduto_baixa
    ADD CONSTRAINT osproduto_baixa_pkey PRIMARY KEY (ordemservicoid, produtoid);


--
-- TOC entry 4042 (class 2606 OID 17632)
-- Name: osproduto osproduto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osproduto
    ADD CONSTRAINT osproduto_pkey PRIMARY KEY (ordemservicoid, produtoid);


--
-- TOC entry 4044 (class 2606 OID 17650)
-- Name: osservico osservico_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osservico
    ADD CONSTRAINT osservico_pkey PRIMARY KEY (ordemservicoid, servicoid);


--
-- TOC entry 4069 (class 2606 OID 63537)
-- Name: pagamento_config pagamento_config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagamento_config
    ADD CONSTRAINT pagamento_config_pkey PRIMARY KEY (empresa_id);


--
-- TOC entry 4067 (class 2606 OID 63495)
-- Name: pagamento_evento pagamento_evento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagamento_evento
    ADD CONSTRAINT pagamento_evento_pkey PRIMARY KEY (id);


--
-- TOC entry 4065 (class 2606 OID 63480)
-- Name: pagamento pagamento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagamento
    ADD CONSTRAINT pagamento_pkey PRIMARY KEY (id);


--
-- TOC entry 4073 (class 2606 OID 69380)
-- Name: peca peca_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.peca
    ADD CONSTRAINT peca_pkey PRIMARY KEY (id);


--
-- TOC entry 3988 (class 2606 OID 17402)
-- Name: perfil perfil_nome_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfil
    ADD CONSTRAINT perfil_nome_key UNIQUE (nome);


--
-- TOC entry 3990 (class 2606 OID 17400)
-- Name: perfil perfil_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfil
    ADD CONSTRAINT perfil_pkey PRIMARY KEY (id);


--
-- TOC entry 4024 (class 2606 OID 17520)
-- Name: perfilpermissao perfilpermissao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfilpermissao
    ADD CONSTRAINT perfilpermissao_pkey PRIMARY KEY (perfilid, permissaoid);


--
-- TOC entry 3984 (class 2606 OID 17390)
-- Name: permissao permissao_nome_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissao
    ADD CONSTRAINT permissao_nome_key UNIQUE (nome);


--
-- TOC entry 3986 (class 2606 OID 17388)
-- Name: permissao permissao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissao
    ADD CONSTRAINT permissao_pkey PRIMARY KEY (id);


--
-- TOC entry 4022 (class 2606 OID 17512)
-- Name: produto produto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT produto_pkey PRIMARY KEY (id);


--
-- TOC entry 4079 (class 2606 OID 87995)
-- Name: produtoentrada produtoentrada_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtoentrada
    ADD CONSTRAINT produtoentrada_pkey PRIMARY KEY (id);


--
-- TOC entry 4081 (class 2606 OID 93632)
-- Name: produtogrupo produtogrupo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtogrupo
    ADD CONSTRAINT produtogrupo_pkey PRIMARY KEY (id);


--
-- TOC entry 4018 (class 2606 OID 17495)
-- Name: servico servico_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.servico
    ADD CONSTRAINT servico_codigo_key UNIQUE (codigo);


--
-- TOC entry 4020 (class 2606 OID 17493)
-- Name: servico servico_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.servico
    ADD CONSTRAINT servico_pkey PRIMARY KEY (id);


--
-- TOC entry 3992 (class 2606 OID 17410)
-- Name: setor setor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.setor
    ADD CONSTRAINT setor_pkey PRIMARY KEY (id);


--
-- TOC entry 4016 (class 2606 OID 17478)
-- Name: tiposervico tiposervico_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tiposervico
    ADD CONSTRAINT tiposervico_pkey PRIMARY KEY (id);


--
-- TOC entry 4058 (class 2606 OID 50477)
-- Name: transacao transacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transacao
    ADD CONSTRAINT transacao_pkey PRIMARY KEY (id);


--
-- TOC entry 4083 (class 2606 OID 93684)
-- Name: unidademedida unidademedida_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unidademedida
    ADD CONSTRAINT unidademedida_pkey PRIMARY KEY (id);


--
-- TOC entry 4085 (class 2606 OID 93686)
-- Name: unidademedida unidademedida_sigla_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unidademedida
    ADD CONSTRAINT unidademedida_sigla_key UNIQUE (sigla);


--
-- TOC entry 3995 (class 2606 OID 17423)
-- Name: usuario usuario_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_email_key UNIQUE (email);


--
-- TOC entry 3997 (class 2606 OID 17421)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 4026 (class 2606 OID 17540)
-- Name: veiculo veiculo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.veiculo
    ADD CONSTRAINT veiculo_pkey PRIMARY KEY (id);


--
-- TOC entry 4028 (class 2606 OID 17542)
-- Name: veiculo veiculo_placa_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.veiculo
    ADD CONSTRAINT veiculo_placa_key UNIQUE (placa);


--
-- TOC entry 4040 (class 2606 OID 17619)
-- Name: venda vendaonline_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT vendaonline_pkey PRIMARY KEY (id);


--
-- TOC entry 4077 (class 2606 OID 81327)
-- Name: vendaproduto vendaproduto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vendaproduto
    ADD CONSTRAINT vendaproduto_pkey PRIMARY KEY (id);


--
-- TOC entry 4053 (class 1259 OID 26510)
-- Name: idx_checklist_modelo_item_modelo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_checklist_modelo_item_modelo ON public.checklist_modelo_item USING btree (modelo_id);


--
-- TOC entry 4006 (class 1259 OID 17753)
-- Name: idx_cliente_cpfcnpj; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cliente_cpfcnpj ON public.cliente USING btree (cpfcnpj);


--
-- TOC entry 4092 (class 1259 OID 102859)
-- Name: idx_nfe_cliente; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_nfe_cliente ON public.nfe USING btree (clienteid);


--
-- TOC entry 4100 (class 1259 OID 102884)
-- Name: idx_nfe_item_nfe; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_nfe_item_nfe ON public.nfe_item USING btree (nfe_id);


--
-- TOC entry 4101 (class 1259 OID 102885)
-- Name: idx_nfe_item_produto; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_nfe_item_produto ON public.nfe_item USING btree (produtoid);


--
-- TOC entry 4093 (class 1259 OID 102860)
-- Name: idx_nfe_ordemservico; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_nfe_ordemservico ON public.nfe USING btree (ordemservicoid);


--
-- TOC entry 4094 (class 1259 OID 102862)
-- Name: idx_nfe_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_nfe_status ON public.nfe USING btree (status);


--
-- TOC entry 4095 (class 1259 OID 102861)
-- Name: idx_nfe_venda; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_nfe_venda ON public.nfe USING btree (vendaid);


--
-- TOC entry 4029 (class 1259 OID 37234)
-- Name: idx_ordemservico_clienteid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ordemservico_clienteid ON public.ordemservico USING btree (clienteid);


--
-- TOC entry 4030 (class 1259 OID 37233)
-- Name: idx_ordemservico_setorid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ordemservico_setorid ON public.ordemservico USING btree (setorid);


--
-- TOC entry 4031 (class 1259 OID 17755)
-- Name: idx_os_cliente; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_os_cliente ON public.ordemservico USING btree (clienteid);


--
-- TOC entry 4032 (class 1259 OID 57671)
-- Name: idx_os_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_os_status ON public.ordemservico USING btree (status);


--
-- TOC entry 4056 (class 1259 OID 63701)
-- Name: idx_transacao_ordemservicoid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_transacao_ordemservicoid ON public.transacao USING btree (ordemservicoid);


--
-- TOC entry 3993 (class 1259 OID 17752)
-- Name: idx_usuario_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_usuario_email ON public.usuario USING btree (email);


--
-- TOC entry 4059 (class 1259 OID 61181)
-- Name: osaprovacao_ordem_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX osaprovacao_ordem_idx ON public.osaprovacao USING btree (ordemservicoid);


--
-- TOC entry 4164 (class 2620 OID 77689)
-- Name: ordemservico ordemservico_status_estorno; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER ordemservico_status_estorno AFTER UPDATE OF status ON public.ordemservico FOR EACH ROW EXECUTE FUNCTION public.trg_os_status_estornar();


--
-- TOC entry 4165 (class 2620 OID 26512)
-- Name: checklist_modelo trg_checklist_modelo_updated; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_checklist_modelo_updated BEFORE UPDATE ON public.checklist_modelo FOR EACH ROW EXECUTE FUNCTION public.set_checklist_modelo_updated_at();


--
-- TOC entry 4162 (class 2620 OID 84820)
-- Name: produto trg_fill_titulo_marketplace; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_fill_titulo_marketplace BEFORE INSERT OR UPDATE OF "tituloMarketplace", titulo ON public.produto FOR EACH ROW EXECUTE FUNCTION public.fn_fill_titulo_marketplace();


--
-- TOC entry 4163 (class 2620 OID 84821)
-- Name: produto trg_set_status_estoque; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_set_status_estoque BEFORE INSERT OR UPDATE OF estoque, estoqueminimo ON public.produto FOR EACH ROW EXECUTE FUNCTION public.fn_set_status_estoque();


--
-- TOC entry 4134 (class 2606 OID 50396)
-- Name: bancoconta bancoconta_empresa_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bancoconta
    ADD CONSTRAINT bancoconta_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresa(id);


--
-- TOC entry 4133 (class 2606 OID 26505)
-- Name: checklist_modelo_item checklist_modelo_item_modelo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checklist_modelo_item
    ADD CONSTRAINT checklist_modelo_item_modelo_id_fkey FOREIGN KEY (modelo_id) REFERENCES public.checklist_modelo(id) ON DELETE CASCADE;


--
-- TOC entry 4122 (class 2606 OID 36058)
-- Name: checklist fk_checklist_ordem_servico; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.checklist
    ADD CONSTRAINT fk_checklist_ordem_servico FOREIGN KEY (ordemservicoid) REFERENCES public.ordemservico(id) ON DELETE CASCADE;


--
-- TOC entry 4123 (class 2606 OID 17604)
-- Name: imagemvistoria fk_imagem_vistoria_checklist; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imagemvistoria
    ADD CONSTRAINT fk_imagem_vistoria_checklist FOREIGN KEY (checklistid) REFERENCES public.checklist(id);


--
-- TOC entry 4131 (class 2606 OID 17719)
-- Name: notafiscal fk_nota_fiscal_ordem_servico; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notafiscal
    ADD CONSTRAINT fk_nota_fiscal_ordem_servico FOREIGN KEY (ordemservicoid) REFERENCES public.ordemservico(id);


--
-- TOC entry 4132 (class 2606 OID 17724)
-- Name: notafiscal fk_nota_fiscal_venda_online; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notafiscal
    ADD CONSTRAINT fk_nota_fiscal_venda_online FOREIGN KEY (vendaonlineid) REFERENCES public.venda(id);


--
-- TOC entry 4116 (class 2606 OID 17561)
-- Name: ordemservico fk_ordem_servico_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ordemservico
    ADD CONSTRAINT fk_ordem_servico_cliente FOREIGN KEY (clienteid) REFERENCES public.cliente(id);


--
-- TOC entry 4117 (class 2606 OID 17576)
-- Name: ordemservico fk_ordem_servico_setor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ordemservico
    ADD CONSTRAINT fk_ordem_servico_setor FOREIGN KEY (setorid) REFERENCES public.setor(id);


--
-- TOC entry 4118 (class 2606 OID 17571)
-- Name: ordemservico fk_ordem_servico_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ordemservico
    ADD CONSTRAINT fk_ordem_servico_usuario FOREIGN KEY (usuariocriadorid) REFERENCES public.usuario(id);


--
-- TOC entry 4119 (class 2606 OID 36063)
-- Name: ordemservico fk_ordem_servico_veiculo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ordemservico
    ADD CONSTRAINT fk_ordem_servico_veiculo FOREIGN KEY (veiculoid) REFERENCES public.veiculo(id) ON DELETE CASCADE;


--
-- TOC entry 4126 (class 2606 OID 17633)
-- Name: osproduto fk_os_produto_ordem; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osproduto
    ADD CONSTRAINT fk_os_produto_ordem FOREIGN KEY (ordemservicoid) REFERENCES public.ordemservico(id);


--
-- TOC entry 4127 (class 2606 OID 17638)
-- Name: osproduto fk_os_produto_produto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osproduto
    ADD CONSTRAINT fk_os_produto_produto FOREIGN KEY (produtoid) REFERENCES public.produto(id);


--
-- TOC entry 4128 (class 2606 OID 17651)
-- Name: osservico fk_os_servico_ordem; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osservico
    ADD CONSTRAINT fk_os_servico_ordem FOREIGN KEY (ordemservicoid) REFERENCES public.ordemservico(id);


--
-- TOC entry 4129 (class 2606 OID 17656)
-- Name: osservico fk_os_servico_servico; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osservico
    ADD CONSTRAINT fk_os_servico_servico FOREIGN KEY (servicoid) REFERENCES public.servico(id);


--
-- TOC entry 4112 (class 2606 OID 17496)
-- Name: servico fk_servico_tipo_servico; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.servico
    ADD CONSTRAINT fk_servico_tipo_servico FOREIGN KEY (tiposervicoid) REFERENCES public.tiposervico(id);


--
-- TOC entry 4111 (class 2606 OID 17479)
-- Name: tiposervico fk_tipo_servico_categoria; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tiposervico
    ADD CONSTRAINT fk_tipo_servico_categoria FOREIGN KEY (categoriaid) REFERENCES public.categoriaservico(id);


--
-- TOC entry 4115 (class 2606 OID 36068)
-- Name: veiculo fk_veiculo_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.veiculo
    ADD CONSTRAINT fk_veiculo_cliente FOREIGN KEY (clienteid) REFERENCES public.cliente(id) ON DELETE CASCADE;


--
-- TOC entry 4124 (class 2606 OID 17620)
-- Name: venda fk_venda_online_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT fk_venda_online_cliente FOREIGN KEY (clienteid) REFERENCES public.cliente(id);


--
-- TOC entry 4153 (class 2606 OID 98391)
-- Name: fornecedorprodutos fornecedorprodutos_fornecedorid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fornecedorprodutos
    ADD CONSTRAINT fornecedorprodutos_fornecedorid_fkey FOREIGN KEY (fornecedorid) REFERENCES public.fornecedor(id);


--
-- TOC entry 4154 (class 2606 OID 98562)
-- Name: fornecedorprodutos fornecedorprodutos_produtoid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fornecedorprodutos
    ADD CONSTRAINT fornecedorprodutos_produtoid_fkey FOREIGN KEY (produtoid) REFERENCES public.produto(id) ON DELETE CASCADE;


--
-- TOC entry 4155 (class 2606 OID 102844)
-- Name: nfe nfe_clienteid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe
    ADD CONSTRAINT nfe_clienteid_fkey FOREIGN KEY (clienteid) REFERENCES public.cliente(id);


--
-- TOC entry 4161 (class 2606 OID 109880)
-- Name: nfe_config nfe_config_empresaid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe_config
    ADD CONSTRAINT nfe_config_empresaid_fkey FOREIGN KEY (empresaid) REFERENCES public.empresa(id) ON DELETE CASCADE;


--
-- TOC entry 4156 (class 2606 OID 104289)
-- Name: nfe nfe_empresaid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe
    ADD CONSTRAINT nfe_empresaid_fkey FOREIGN KEY (empresaid) REFERENCES public.empresa(id);


--
-- TOC entry 4159 (class 2606 OID 102874)
-- Name: nfe_item nfe_item_nfe_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe_item
    ADD CONSTRAINT nfe_item_nfe_id_fkey FOREIGN KEY (nfe_id) REFERENCES public.nfe(id) ON DELETE CASCADE;


--
-- TOC entry 4160 (class 2606 OID 102879)
-- Name: nfe_item nfe_item_produtoid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe_item
    ADD CONSTRAINT nfe_item_produtoid_fkey FOREIGN KEY (produtoid) REFERENCES public.produto(id);


--
-- TOC entry 4157 (class 2606 OID 102849)
-- Name: nfe nfe_ordemservicoid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe
    ADD CONSTRAINT nfe_ordemservicoid_fkey FOREIGN KEY (ordemservicoid) REFERENCES public.ordemservico(id) ON DELETE SET NULL;


--
-- TOC entry 4158 (class 2606 OID 102854)
-- Name: nfe nfe_vendaid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfe
    ADD CONSTRAINT nfe_vendaid_fkey FOREIGN KEY (vendaid) REFERENCES public.venda(id) ON DELETE SET NULL;


--
-- TOC entry 4144 (class 2606 OID 63551)
-- Name: nfse_config nfse_config_empresa_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nfse_config
    ADD CONSTRAINT nfse_config_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresa(id) ON DELETE CASCADE;


--
-- TOC entry 4120 (class 2606 OID 37228)
-- Name: ordemservico ordemservico_checklist_modelo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ordemservico
    ADD CONSTRAINT ordemservico_checklist_modelo_id_fkey FOREIGN KEY (checklist_modelo_id) REFERENCES public.checklist_modelo(id);


--
-- TOC entry 4121 (class 2606 OID 69392)
-- Name: ordemservico ordemservico_pecaid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ordemservico
    ADD CONSTRAINT ordemservico_pecaid_fkey FOREIGN KEY (pecaid) REFERENCES public.peca(id);


--
-- TOC entry 4139 (class 2606 OID 86518)
-- Name: osaprovacao osaprovacao_aprovador_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osaprovacao
    ADD CONSTRAINT osaprovacao_aprovador_usuario_id_fkey FOREIGN KEY (aprovador_usuario_id) REFERENCES public.usuario(id);


--
-- TOC entry 4140 (class 2606 OID 61176)
-- Name: osaprovacao osaprovacao_ordemservicoid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osaprovacao
    ADD CONSTRAINT osaprovacao_ordemservicoid_fkey FOREIGN KEY (ordemservicoid) REFERENCES public.ordemservico(id) ON DELETE CASCADE;


--
-- TOC entry 4147 (class 2606 OID 77614)
-- Name: osproduto_baixa osproduto_baixa_ordemservicoid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osproduto_baixa
    ADD CONSTRAINT osproduto_baixa_ordemservicoid_fkey FOREIGN KEY (ordemservicoid) REFERENCES public.ordemservico(id) ON DELETE CASCADE;


--
-- TOC entry 4148 (class 2606 OID 77619)
-- Name: osproduto_baixa osproduto_baixa_produtoid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osproduto_baixa
    ADD CONSTRAINT osproduto_baixa_produtoid_fkey FOREIGN KEY (produtoid) REFERENCES public.produto(id);


--
-- TOC entry 4130 (class 2606 OID 63722)
-- Name: osservico osservico_idusuariorealizador_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.osservico
    ADD CONSTRAINT osservico_idusuariorealizador_fkey FOREIGN KEY (idusuariorealizador) REFERENCES public.usuario(id) ON UPDATE CASCADE;


--
-- TOC entry 4143 (class 2606 OID 63538)
-- Name: pagamento_config pagamento_config_empresa_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagamento_config
    ADD CONSTRAINT pagamento_config_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresa(id) ON DELETE CASCADE;


--
-- TOC entry 4142 (class 2606 OID 63496)
-- Name: pagamento_evento pagamento_evento_pagamentoid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagamento_evento
    ADD CONSTRAINT pagamento_evento_pagamentoid_fkey FOREIGN KEY (pagamentoid) REFERENCES public.pagamento(id);


--
-- TOC entry 4141 (class 2606 OID 63481)
-- Name: pagamento pagamento_ordemservicoid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagamento
    ADD CONSTRAINT pagamento_ordemservicoid_fkey FOREIGN KEY (ordemservicoid) REFERENCES public.ordemservico(id);


--
-- TOC entry 4145 (class 2606 OID 69381)
-- Name: peca peca_clienteid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.peca
    ADD CONSTRAINT peca_clienteid_fkey FOREIGN KEY (clienteid) REFERENCES public.cliente(id);


--
-- TOC entry 4146 (class 2606 OID 69386)
-- Name: peca peca_veiculoid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.peca
    ADD CONSTRAINT peca_veiculoid_fkey FOREIGN KEY (veiculoid) REFERENCES public.veiculo(id);


--
-- TOC entry 4113 (class 2606 OID 17521)
-- Name: perfilpermissao perfilpermissao_perfil_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfilpermissao
    ADD CONSTRAINT perfilpermissao_perfil_fkey FOREIGN KEY (perfilid) REFERENCES public.perfil(id);


--
-- TOC entry 4114 (class 2606 OID 17526)
-- Name: perfilpermissao perfilpermissao_permissao_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfilpermissao
    ADD CONSTRAINT perfilpermissao_permissao_fkey FOREIGN KEY (permissaoid) REFERENCES public.permissao(id);


--
-- TOC entry 4151 (class 2606 OID 90740)
-- Name: produtoentrada produtoentrada_fornecedorid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtoentrada
    ADD CONSTRAINT produtoentrada_fornecedorid_fkey FOREIGN KEY (fornecedorid) REFERENCES public.fornecedor(id);


--
-- TOC entry 4152 (class 2606 OID 87996)
-- Name: produtoentrada produtoentrada_produtoid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtoentrada
    ADD CONSTRAINT produtoentrada_produtoid_fkey FOREIGN KEY (produtoid) REFERENCES public.produto(id);


--
-- TOC entry 4135 (class 2606 OID 50483)
-- Name: transacao transacao_banco_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transacao
    ADD CONSTRAINT transacao_banco_id_fkey FOREIGN KEY (banco_id) REFERENCES public.bancoconta(id) ON UPDATE RESTRICT;


--
-- TOC entry 4136 (class 2606 OID 50478)
-- Name: transacao transacao_cliente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transacao
    ADD CONSTRAINT transacao_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.cliente(id) ON UPDATE CASCADE;


--
-- TOC entry 4137 (class 2606 OID 63696)
-- Name: transacao transacao_ordemservicoid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transacao
    ADD CONSTRAINT transacao_ordemservicoid_fkey FOREIGN KEY (ordemservicoid) REFERENCES public.ordemservico(id) ON DELETE SET NULL;


--
-- TOC entry 4138 (class 2606 OID 93352)
-- Name: transacao transacao_vendaid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transacao
    ADD CONSTRAINT transacao_vendaid_fkey FOREIGN KEY (vendaid) REFERENCES public.venda(id);


--
-- TOC entry 4108 (class 2606 OID 24716)
-- Name: usuario usuario_auth_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_auth_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- TOC entry 4109 (class 2606 OID 17429)
-- Name: usuario usuario_perfilid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_perfilid_fkey FOREIGN KEY (perfilid) REFERENCES public.perfil(id);


--
-- TOC entry 4110 (class 2606 OID 17424)
-- Name: usuario usuario_setorid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_setorid_fkey FOREIGN KEY (setorid) REFERENCES public.setor(id);


--
-- TOC entry 4125 (class 2606 OID 81306)
-- Name: venda vendaonline_usuariocriadorid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT vendaonline_usuariocriadorid_fkey FOREIGN KEY (usuariocriadorid) REFERENCES public.usuario(id);


--
-- TOC entry 4149 (class 2606 OID 81333)
-- Name: vendaproduto vendaproduto_produtoid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vendaproduto
    ADD CONSTRAINT vendaproduto_produtoid_fkey FOREIGN KEY (produtoid) REFERENCES public.produto(id);


--
-- TOC entry 4150 (class 2606 OID 81328)
-- Name: vendaproduto vendaproduto_vendaId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vendaproduto
    ADD CONSTRAINT "vendaproduto_vendaId_fkey" FOREIGN KEY (venda_id) REFERENCES public.venda(id);


--
-- TOC entry 4314 (class 0 OID 98379)
-- Dependencies: 454
-- Name: fornecedorprodutos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.fornecedorprodutos ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 4324 (class 0 OID 0)
-- Dependencies: 425
-- Name: TABLE bancoconta; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.bancoconta TO anon;
GRANT ALL ON TABLE public.bancoconta TO authenticated;
GRANT ALL ON TABLE public.bancoconta TO service_role;


--
-- TOC entry 4325 (class 0 OID 0)
-- Dependencies: 426
-- Name: SEQUENCE banco_conta_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.banco_conta_id_seq TO anon;
GRANT ALL ON SEQUENCE public.banco_conta_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.banco_conta_id_seq TO service_role;


--
-- TOC entry 4326 (class 0 OID 0)
-- Dependencies: 384
-- Name: TABLE categoriaservico; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.categoriaservico TO anon;
GRANT ALL ON TABLE public.categoriaservico TO authenticated;
GRANT ALL ON TABLE public.categoriaservico TO service_role;


--
-- TOC entry 4327 (class 0 OID 0)
-- Dependencies: 383
-- Name: SEQUENCE categoriaservico_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.categoriaservico_id_seq TO anon;
GRANT ALL ON SEQUENCE public.categoriaservico_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.categoriaservico_id_seq TO service_role;


--
-- TOC entry 4328 (class 0 OID 0)
-- Dependencies: 453
-- Name: TABLE categoriatransacao; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.categoriatransacao TO anon;
GRANT ALL ON TABLE public.categoriatransacao TO authenticated;
GRANT ALL ON TABLE public.categoriatransacao TO service_role;


--
-- TOC entry 4329 (class 0 OID 0)
-- Dependencies: 452
-- Name: SEQUENCE categoriatransacao_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.categoriatransacao_id_seq TO anon;
GRANT ALL ON SEQUENCE public.categoriatransacao_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.categoriatransacao_id_seq TO service_role;


--
-- TOC entry 4330 (class 0 OID 0)
-- Dependencies: 410
-- Name: TABLE checklist; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.checklist TO anon;
GRANT ALL ON TABLE public.checklist TO authenticated;
GRANT ALL ON TABLE public.checklist TO service_role;


--
-- TOC entry 4331 (class 0 OID 0)
-- Dependencies: 409
-- Name: SEQUENCE checklist_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.checklist_id_seq TO anon;
GRANT ALL ON SEQUENCE public.checklist_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.checklist_id_seq TO service_role;


--
-- TOC entry 4332 (class 0 OID 0)
-- Dependencies: 422
-- Name: TABLE checklist_modelo; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.checklist_modelo TO anon;
GRANT ALL ON TABLE public.checklist_modelo TO authenticated;
GRANT ALL ON TABLE public.checklist_modelo TO service_role;


--
-- TOC entry 4333 (class 0 OID 0)
-- Dependencies: 421
-- Name: SEQUENCE checklist_modelo_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.checklist_modelo_id_seq TO anon;
GRANT ALL ON SEQUENCE public.checklist_modelo_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.checklist_modelo_id_seq TO service_role;


--
-- TOC entry 4334 (class 0 OID 0)
-- Dependencies: 424
-- Name: TABLE checklist_modelo_item; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.checklist_modelo_item TO anon;
GRANT ALL ON TABLE public.checklist_modelo_item TO authenticated;
GRANT ALL ON TABLE public.checklist_modelo_item TO service_role;


--
-- TOC entry 4335 (class 0 OID 0)
-- Dependencies: 423
-- Name: SEQUENCE checklist_modelo_item_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.checklist_modelo_item_id_seq TO anon;
GRANT ALL ON SEQUENCE public.checklist_modelo_item_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.checklist_modelo_item_id_seq TO service_role;


--
-- TOC entry 4336 (class 0 OID 0)
-- Dependencies: 393
-- Name: TABLE cliente; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.cliente TO anon;
GRANT ALL ON TABLE public.cliente TO authenticated;
GRANT ALL ON TABLE public.cliente TO service_role;


--
-- TOC entry 4337 (class 0 OID 0)
-- Dependencies: 392
-- Name: SEQUENCE cliente_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.cliente_id_seq TO anon;
GRANT ALL ON SEQUENCE public.cliente_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.cliente_id_seq TO service_role;


--
-- TOC entry 4338 (class 0 OID 0)
-- Dependencies: 395
-- Name: TABLE empresa; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.empresa TO anon;
GRANT ALL ON TABLE public.empresa TO authenticated;
GRANT ALL ON TABLE public.empresa TO service_role;


--
-- TOC entry 4339 (class 0 OID 0)
-- Dependencies: 394
-- Name: SEQUENCE empresa_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.empresa_id_seq TO anon;
GRANT ALL ON SEQUENCE public.empresa_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.empresa_id_seq TO service_role;


--
-- TOC entry 4340 (class 0 OID 0)
-- Dependencies: 397
-- Name: TABLE fornecedor; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.fornecedor TO anon;
GRANT ALL ON TABLE public.fornecedor TO authenticated;
GRANT ALL ON TABLE public.fornecedor TO service_role;


--
-- TOC entry 4341 (class 0 OID 0)
-- Dependencies: 396
-- Name: SEQUENCE fornecedor_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.fornecedor_id_seq TO anon;
GRANT ALL ON SEQUENCE public.fornecedor_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.fornecedor_id_seq TO service_role;


--
-- TOC entry 4342 (class 0 OID 0)
-- Dependencies: 454
-- Name: TABLE fornecedorprodutos; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.fornecedorprodutos TO anon;
GRANT ALL ON TABLE public.fornecedorprodutos TO authenticated;
GRANT ALL ON TABLE public.fornecedorprodutos TO service_role;


--
-- TOC entry 4343 (class 0 OID 0)
-- Dependencies: 455
-- Name: SEQUENCE fornecedorprodutos_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.fornecedorprodutos_id_seq TO anon;
GRANT ALL ON SEQUENCE public.fornecedorprodutos_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.fornecedorprodutos_id_seq TO service_role;


--
-- TOC entry 4344 (class 0 OID 0)
-- Dependencies: 412
-- Name: TABLE imagemvistoria; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.imagemvistoria TO anon;
GRANT ALL ON TABLE public.imagemvistoria TO authenticated;
GRANT ALL ON TABLE public.imagemvistoria TO service_role;


--
-- TOC entry 4345 (class 0 OID 0)
-- Dependencies: 411
-- Name: SEQUENCE imagemvistoria_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.imagemvistoria_id_seq TO anon;
GRANT ALL ON SEQUENCE public.imagemvistoria_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.imagemvistoria_id_seq TO service_role;


--
-- TOC entry 4346 (class 0 OID 0)
-- Dependencies: 460
-- Name: TABLE nfe; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.nfe TO anon;
GRANT ALL ON TABLE public.nfe TO authenticated;
GRANT ALL ON TABLE public.nfe TO service_role;


--
-- TOC entry 4347 (class 0 OID 0)
-- Dependencies: 468
-- Name: TABLE nfe_config; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.nfe_config TO anon;
GRANT ALL ON TABLE public.nfe_config TO authenticated;
GRANT ALL ON TABLE public.nfe_config TO service_role;


--
-- TOC entry 4349 (class 0 OID 0)
-- Dependencies: 467
-- Name: SEQUENCE nfe_config_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.nfe_config_id_seq TO anon;
GRANT ALL ON SEQUENCE public.nfe_config_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.nfe_config_id_seq TO service_role;


--
-- TOC entry 4351 (class 0 OID 0)
-- Dependencies: 459
-- Name: SEQUENCE nfe_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.nfe_id_seq TO anon;
GRANT ALL ON SEQUENCE public.nfe_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.nfe_id_seq TO service_role;


--
-- TOC entry 4352 (class 0 OID 0)
-- Dependencies: 462
-- Name: TABLE nfe_item; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.nfe_item TO anon;
GRANT ALL ON TABLE public.nfe_item TO authenticated;
GRANT ALL ON TABLE public.nfe_item TO service_role;


--
-- TOC entry 4354 (class 0 OID 0)
-- Dependencies: 461
-- Name: SEQUENCE nfe_item_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.nfe_item_id_seq TO anon;
GRANT ALL ON SEQUENCE public.nfe_item_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.nfe_item_id_seq TO service_role;


--
-- TOC entry 4355 (class 0 OID 0)
-- Dependencies: 438
-- Name: TABLE nfse_config; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.nfse_config TO anon;
GRANT ALL ON TABLE public.nfse_config TO authenticated;
GRANT ALL ON TABLE public.nfse_config TO service_role;


--
-- TOC entry 4356 (class 0 OID 0)
-- Dependencies: 418
-- Name: TABLE notafiscal; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.notafiscal TO anon;
GRANT ALL ON TABLE public.notafiscal TO authenticated;
GRANT ALL ON TABLE public.notafiscal TO service_role;


--
-- TOC entry 4357 (class 0 OID 0)
-- Dependencies: 417
-- Name: SEQUENCE notafiscal_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.notafiscal_id_seq TO anon;
GRANT ALL ON SEQUENCE public.notafiscal_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.notafiscal_id_seq TO service_role;


--
-- TOC entry 4358 (class 0 OID 0)
-- Dependencies: 408
-- Name: TABLE ordemservico; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ordemservico TO anon;
GRANT ALL ON TABLE public.ordemservico TO authenticated;
GRANT ALL ON TABLE public.ordemservico TO service_role;


--
-- TOC entry 4359 (class 0 OID 0)
-- Dependencies: 407
-- Name: SEQUENCE ordemservico_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.ordemservico_id_seq TO anon;
GRANT ALL ON SEQUENCE public.ordemservico_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.ordemservico_id_seq TO service_role;


--
-- TOC entry 4360 (class 0 OID 0)
-- Dependencies: 432
-- Name: TABLE osaprovacao; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.osaprovacao TO anon;
GRANT ALL ON TABLE public.osaprovacao TO authenticated;
GRANT ALL ON TABLE public.osaprovacao TO service_role;


--
-- TOC entry 4362 (class 0 OID 0)
-- Dependencies: 431
-- Name: SEQUENCE osaprovacao_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.osaprovacao_id_seq TO anon;
GRANT ALL ON SEQUENCE public.osaprovacao_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.osaprovacao_id_seq TO service_role;


--
-- TOC entry 4363 (class 0 OID 0)
-- Dependencies: 415
-- Name: TABLE osproduto; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.osproduto TO anon;
GRANT ALL ON TABLE public.osproduto TO authenticated;
GRANT ALL ON TABLE public.osproduto TO service_role;


--
-- TOC entry 4364 (class 0 OID 0)
-- Dependencies: 441
-- Name: TABLE osproduto_baixa; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.osproduto_baixa TO anon;
GRANT ALL ON TABLE public.osproduto_baixa TO authenticated;
GRANT ALL ON TABLE public.osproduto_baixa TO service_role;


--
-- TOC entry 4365 (class 0 OID 0)
-- Dependencies: 416
-- Name: TABLE osservico; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.osservico TO anon;
GRANT ALL ON TABLE public.osservico TO authenticated;
GRANT ALL ON TABLE public.osservico TO service_role;


--
-- TOC entry 4366 (class 0 OID 0)
-- Dependencies: 434
-- Name: TABLE pagamento; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.pagamento TO anon;
GRANT ALL ON TABLE public.pagamento TO authenticated;
GRANT ALL ON TABLE public.pagamento TO service_role;


--
-- TOC entry 4367 (class 0 OID 0)
-- Dependencies: 437
-- Name: TABLE pagamento_config; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.pagamento_config TO anon;
GRANT ALL ON TABLE public.pagamento_config TO authenticated;
GRANT ALL ON TABLE public.pagamento_config TO service_role;


--
-- TOC entry 4368 (class 0 OID 0)
-- Dependencies: 436
-- Name: TABLE pagamento_evento; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.pagamento_evento TO anon;
GRANT ALL ON TABLE public.pagamento_evento TO authenticated;
GRANT ALL ON TABLE public.pagamento_evento TO service_role;


--
-- TOC entry 4370 (class 0 OID 0)
-- Dependencies: 435
-- Name: SEQUENCE pagamento_evento_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.pagamento_evento_id_seq TO anon;
GRANT ALL ON SEQUENCE public.pagamento_evento_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.pagamento_evento_id_seq TO service_role;


--
-- TOC entry 4372 (class 0 OID 0)
-- Dependencies: 433
-- Name: SEQUENCE pagamento_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.pagamento_id_seq TO anon;
GRANT ALL ON SEQUENCE public.pagamento_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.pagamento_id_seq TO service_role;


--
-- TOC entry 4373 (class 0 OID 0)
-- Dependencies: 440
-- Name: TABLE peca; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.peca TO anon;
GRANT ALL ON TABLE public.peca TO authenticated;
GRANT ALL ON TABLE public.peca TO service_role;


--
-- TOC entry 4374 (class 0 OID 0)
-- Dependencies: 439
-- Name: SEQUENCE peca_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.peca_id_seq TO anon;
GRANT ALL ON SEQUENCE public.peca_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.peca_id_seq TO service_role;


--
-- TOC entry 4375 (class 0 OID 0)
-- Dependencies: 388
-- Name: TABLE perfil; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.perfil TO anon;
GRANT ALL ON TABLE public.perfil TO authenticated;
GRANT ALL ON TABLE public.perfil TO service_role;


--
-- TOC entry 4376 (class 0 OID 0)
-- Dependencies: 387
-- Name: SEQUENCE perfil_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.perfil_id_seq TO anon;
GRANT ALL ON SEQUENCE public.perfil_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.perfil_id_seq TO service_role;


--
-- TOC entry 4377 (class 0 OID 0)
-- Dependencies: 404
-- Name: TABLE perfilpermissao; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.perfilpermissao TO anon;
GRANT ALL ON TABLE public.perfilpermissao TO authenticated;
GRANT ALL ON TABLE public.perfilpermissao TO service_role;


--
-- TOC entry 4378 (class 0 OID 0)
-- Dependencies: 386
-- Name: TABLE permissao; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.permissao TO anon;
GRANT ALL ON TABLE public.permissao TO authenticated;
GRANT ALL ON TABLE public.permissao TO service_role;


--
-- TOC entry 4379 (class 0 OID 0)
-- Dependencies: 385
-- Name: SEQUENCE permissao_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.permissao_id_seq TO anon;
GRANT ALL ON SEQUENCE public.permissao_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.permissao_id_seq TO service_role;


--
-- TOC entry 4380 (class 0 OID 0)
-- Dependencies: 403
-- Name: TABLE produto; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.produto TO anon;
GRANT ALL ON TABLE public.produto TO authenticated;
GRANT ALL ON TABLE public.produto TO service_role;


--
-- TOC entry 4381 (class 0 OID 0)
-- Dependencies: 402
-- Name: SEQUENCE produto_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.produto_id_seq TO anon;
GRANT ALL ON SEQUENCE public.produto_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.produto_id_seq TO service_role;


--
-- TOC entry 4382 (class 0 OID 0)
-- Dependencies: 446
-- Name: TABLE produtoentrada; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.produtoentrada TO anon;
GRANT ALL ON TABLE public.produtoentrada TO authenticated;
GRANT ALL ON TABLE public.produtoentrada TO service_role;


--
-- TOC entry 4383 (class 0 OID 0)
-- Dependencies: 447
-- Name: SEQUENCE produtoentrada_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.produtoentrada_id_seq TO anon;
GRANT ALL ON SEQUENCE public.produtoentrada_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.produtoentrada_id_seq TO service_role;


--
-- TOC entry 4384 (class 0 OID 0)
-- Dependencies: 449
-- Name: TABLE produtogrupo; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.produtogrupo TO anon;
GRANT ALL ON TABLE public.produtogrupo TO authenticated;
GRANT ALL ON TABLE public.produtogrupo TO service_role;


--
-- TOC entry 4385 (class 0 OID 0)
-- Dependencies: 448
-- Name: SEQUENCE produtogrupo_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.produtogrupo_id_seq TO anon;
GRANT ALL ON SEQUENCE public.produtogrupo_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.produtogrupo_id_seq TO service_role;


--
-- TOC entry 4386 (class 0 OID 0)
-- Dependencies: 401
-- Name: TABLE servico; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.servico TO anon;
GRANT ALL ON TABLE public.servico TO authenticated;
GRANT ALL ON TABLE public.servico TO service_role;


--
-- TOC entry 4387 (class 0 OID 0)
-- Dependencies: 400
-- Name: SEQUENCE servico_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.servico_id_seq TO anon;
GRANT ALL ON SEQUENCE public.servico_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.servico_id_seq TO service_role;


--
-- TOC entry 4388 (class 0 OID 0)
-- Dependencies: 390
-- Name: TABLE setor; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.setor TO anon;
GRANT ALL ON TABLE public.setor TO authenticated;
GRANT ALL ON TABLE public.setor TO service_role;


--
-- TOC entry 4389 (class 0 OID 0)
-- Dependencies: 389
-- Name: SEQUENCE setor_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.setor_id_seq TO anon;
GRANT ALL ON SEQUENCE public.setor_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.setor_id_seq TO service_role;


--
-- TOC entry 4390 (class 0 OID 0)
-- Dependencies: 399
-- Name: TABLE tiposervico; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.tiposervico TO anon;
GRANT ALL ON TABLE public.tiposervico TO authenticated;
GRANT ALL ON TABLE public.tiposervico TO service_role;


--
-- TOC entry 4391 (class 0 OID 0)
-- Dependencies: 398
-- Name: SEQUENCE tiposervico_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.tiposervico_id_seq TO anon;
GRANT ALL ON SEQUENCE public.tiposervico_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.tiposervico_id_seq TO service_role;


--
-- TOC entry 4392 (class 0 OID 0)
-- Dependencies: 427
-- Name: TABLE transacao; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.transacao TO anon;
GRANT ALL ON TABLE public.transacao TO authenticated;
GRANT ALL ON TABLE public.transacao TO service_role;


--
-- TOC entry 4393 (class 0 OID 0)
-- Dependencies: 428
-- Name: SEQUENCE transacao_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.transacao_id_seq TO anon;
GRANT ALL ON SEQUENCE public.transacao_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.transacao_id_seq TO service_role;


--
-- TOC entry 4394 (class 0 OID 0)
-- Dependencies: 451
-- Name: TABLE unidademedida; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.unidademedida TO anon;
GRANT ALL ON TABLE public.unidademedida TO authenticated;
GRANT ALL ON TABLE public.unidademedida TO service_role;


--
-- TOC entry 4395 (class 0 OID 0)
-- Dependencies: 450
-- Name: SEQUENCE unidademedida_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.unidademedida_id_seq TO anon;
GRANT ALL ON SEQUENCE public.unidademedida_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.unidademedida_id_seq TO service_role;


--
-- TOC entry 4396 (class 0 OID 0)
-- Dependencies: 391
-- Name: TABLE usuario; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.usuario TO anon;
GRANT ALL ON TABLE public.usuario TO authenticated;
GRANT ALL ON TABLE public.usuario TO service_role;


--
-- TOC entry 4397 (class 0 OID 0)
-- Dependencies: 406
-- Name: TABLE veiculo; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.veiculo TO anon;
GRANT ALL ON TABLE public.veiculo TO authenticated;
GRANT ALL ON TABLE public.veiculo TO service_role;


--
-- TOC entry 4398 (class 0 OID 0)
-- Dependencies: 405
-- Name: SEQUENCE veiculo_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.veiculo_id_seq TO anon;
GRANT ALL ON SEQUENCE public.veiculo_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.veiculo_id_seq TO service_role;


--
-- TOC entry 4399 (class 0 OID 0)
-- Dependencies: 414
-- Name: TABLE venda; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.venda TO anon;
GRANT ALL ON TABLE public.venda TO authenticated;
GRANT ALL ON TABLE public.venda TO service_role;


--
-- TOC entry 4400 (class 0 OID 0)
-- Dependencies: 413
-- Name: SEQUENCE vendaonline_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.vendaonline_id_seq TO anon;
GRANT ALL ON SEQUENCE public.vendaonline_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.vendaonline_id_seq TO service_role;


--
-- TOC entry 4401 (class 0 OID 0)
-- Dependencies: 442
-- Name: TABLE vendaproduto; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.vendaproduto TO anon;
GRANT ALL ON TABLE public.vendaproduto TO authenticated;
GRANT ALL ON TABLE public.vendaproduto TO service_role;


--
-- TOC entry 4402 (class 0 OID 0)
-- Dependencies: 443
-- Name: SEQUENCE vendaproduto_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.vendaproduto_id_seq TO anon;
GRANT ALL ON SEQUENCE public.vendaproduto_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.vendaproduto_id_seq TO service_role;


-- Completed on 2025-12-09 18:30:41

--
-- PostgreSQL database dump complete
--

\unrestrict ZnPdZw9XPfvLBbq0mNjMF0M0dfDuTRXznYjmmNjHtaHApeqrvtJNqUkszNZIvFu

