create table public.bancoconta (
  id bigint generated by default as identity not null,
  titulo text not null,
  created_at timestamp with time zone not null,
  valorinicial real not null,
  agencia text null,
  contanumero text null,
  tipo public.banco_tipo not null default 'CORRENTE'::banco_tipo,
  proprietario text null,
  empresa_id integer null,
  updated_at timestamp with time zone not null,
  ativo boolean null default true,
  constraint banco_conta_pkey primary key (id),
  constraint bancoconta_empresa_id_fkey foreign KEY (empresa_id) references empresa (id)
) TABLESPACE pg_default;

create table public.categoriaservico (
  id integer generated always as identity not null,
  nome character varying not null,
  descricao character varying null,
  constraint categoriaservico_pkey primary key (id)
) TABLESPACE pg_default;

create table public.categoriatransacao (
  id integer generated always as identity not null,
  nome text not null,
  descricao text null,
  ativo boolean not null default true,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  constraint categoriatransacao_pkey primary key (id),
  constraint categoria_transacao_nome_key unique (nome)
) TABLESPACE pg_default;

create table public.checklist (
  id integer generated always as identity not null,
  ordemservicoid integer not null,
  item character varying not null,
  status public.enum_status_checklist not null default 'OK'::enum_status_checklist,
  observacao character varying null,
  createdat timestamp without time zone null default now(),
  created_by uuid null,
  constraint checklist_pkey primary key (id),
  constraint checklist_created_by_fkey foreign KEY (created_by) references usuario (id),
  constraint fk_checklist_ordem_servico foreign KEY (ordemservicoid) references ordemservico (id) on delete CASCADE
) TABLESPACE pg_default;

create unique INDEX IF not exists uniq_checklist_os_item on public.checklist using btree (ordemservicoid, item) TABLESPACE pg_default;

create table public.checklist_modelo (
  id integer generated always as identity not null,
  nome character varying not null,
  descricao character varying null,
  categoria character varying null,
  ativo boolean not null default true,
  criado_em timestamp without time zone not null default now(),
  atualizado_em timestamp without time zone not null default now(),
  constraint checklist_modelo_pkey primary key (id),
  constraint checklist_modelo_nome_key unique (nome)
) TABLESPACE pg_default;

create trigger trg_checklist_modelo_updated BEFORE
update on checklist_modelo for EACH row
execute FUNCTION set_checklist_modelo_updated_at ();

create table public.cliente (
  id integer generated always as identity not null,
  tipopessoa public.enum_tipopessoa not null,
  cpfcnpj character varying not null,
  nomerazaosocial character varying not null,
  email character varying not null,
  telefone character varying null,
  endereco character varying null,
  cidade character varying not null,
  estado character varying not null,
  cep character varying null,
  inscricaoestadual character varying null,
  inscricaomunicipal character varying null,
  codigomunicipio character varying null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  status public.enum_status_cliente null default 'ATIVO'::enum_status_cliente,
  endereconumero text null,
  enderecocomplemento text null,
  bairro text null,
  created_by uuid null,
  updated_by uuid null,
  is_deleted boolean not null default false,
  deleted_at timestamp with time zone null,
  deleted_by uuid null,
  rank public.cliente_rank null,
  ranked_by uuid null,
  ranked_at timestamp with time zone null,
  user_id uuid null,
  constraint cliente_pkey primary key (id),
  constraint cliente_user_id_key unique (user_id),
  constraint cliente_nomerazaosocial_key unique (nomerazaosocial),
  constraint cliente_cpfcnpj_key unique (cpfcnpj),
  constraint cliente_user_id_fkey foreign KEY (user_id) references auth.users (id),
  constraint cliente_created_by_fkey foreign KEY (created_by) references usuario (id),
  constraint cliente_ranked_by_fkey foreign KEY (ranked_by) references usuario (id),
  constraint cliente_updated_by_fkey foreign KEY (updated_by) references usuario (id),
  constraint cliente_deleted_by_fkey foreign KEY (deleted_by) references usuario (id),
  constraint cliente_email_formato_chk check (
    (
      (email)::text ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'::text
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_cliente_cpfcnpj on public.cliente using btree (cpfcnpj) TABLESPACE pg_default;

create index IF not exists cliente_user_id_idx on public.cliente using btree (user_id) TABLESPACE pg_default;

create table public.cliente_endereco (
  id bigint generated always as identity not null,
  cliente_id integer not null,
  nome_identificador text null,
  cep text not null,
  logradouro text not null,
  numero text not null,
  complemento text null,
  bairro text null,
  cidade text not null,
  estado text not null,
  principal boolean null default false,
  created_at timestamp with time zone null default now(),
  constraint cliente_endereco_pkey primary key (id),
  constraint cliente_endereco_cliente_id_fkey foreign KEY (cliente_id) references cliente (id)
) TABLESPACE pg_default;

create table public.config_geral (
  id bigint generated by default as identity not null,
  aviso_pagamento boolean not null default false,
  created_at timestamp with time zone not null default now(),
  checklist_obrigatorio boolean not null default true,
  alerta_estoque_pdv boolean not null default true,
  habilitar_emissao_nfe boolean not null default false,
  constraint config_geral_pkey primary key (id)
) TABLESPACE pg_default;

create table public.cores_veiculos (
  id integer generated always as identity not null,
  nome text not null,
  ativo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  created_by uuid null,
  updated_at timestamp with time zone not null default now(),
  updated_by uuid null,
  constraint cores_veiculos_pkey primary key (id),
  constraint cores_veiculos_nome_key unique (nome),
  constraint cores_veiculos_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint cores_veiculos_updated_by_fkey foreign KEY (updated_by) references auth.users (id)
) TABLESPACE pg_default;

create table public.empresa (
  id integer generated always as identity not null,
  cnpj character varying not null,
  razaosocial character varying not null,
  nomefantasia character varying null,
  inscricaoestadual character varying null,
  inscricaomunicipal character varying null,
  endereco character varying not null,
  codigomunicipio character varying not null,
  regimetributario character varying not null,
  certificadocaminho character varying null,
  cschomologacao character varying null,
  cscproducao character varying null,
  ambiente character varying null default 'HOMOLOGACAO'::character varying,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  bairro character varying null,
  numero character varying null,
  complemento character varying null,
  cep character varying null,
  uf character varying(2) null,
  codigopais character varying null default '1058'::character varying,
  nomepais character varying null default 'BRASIL'::character varying,
  telefone character varying null,
  cnae character varying null,
  inscricaoestadualst character varying null,
  certificadosenha character varying null,
  constraint empresa_pkey primary key (id),
  constraint empresa_cnpj_key unique (cnpj),
  constraint empresa_ambiente_check check (
    (
      (ambiente)::text = any (
        array[
          ('HOMOLOGACAO'::character varying)::text,
          ('PRODUCAO'::character varying)::text
        ]
      )
    )
  ),
  constraint empresa_regimetributario_check check (
    (
      (regimetributario)::text = any (
        array[
          ('1'::character varying)::text,
          ('2'::character varying)::text,
          ('3'::character varying)::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create table public.entrada (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  fornecedorid integer null,
  fiscal boolean not null default false,
  notachave text null,
  tipo public.enum_tipos_entrada not null default 'COMPRA_FORNECEDOR'::enum_tipos_entrada,
  status public.enum_staus_entrada not null default 'RASCUNHO'::enum_staus_entrada,
  constraint produtoentrada_pkey primary key (id),
  constraint produtoentrada_fornecedorid_fkey foreign KEY (fornecedorid) references fornecedor (id)
) TABLESPACE pg_default;

create table public.entradaitens (
  id bigint generated by default as identity not null,
  produto_id integer not null,
  unidade public.unidade_medida not null default 'UN'::unidade_medida,
  quantidade numeric not null,
  precovenda numeric not null,
  entrada_id bigint not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  ncm text null,
  cest text null,
  csosn text null,
  referencia text null,
  titulo text null,
  "cClassTrib" text null,
  "cstIbs" text null,
  "cstCbs" text null,
  cst text null,
  aliquotaicms numeric null,
  cfop text null,
  cst_pis text null,
  aliquota_pis numeric(5, 2) null,
  cst_cofins text null,
  aliquota_cofins numeric(5, 2) null,
  constraint entradaitens_pkey primary key (id),
  constraint entradaitens_entrada_id_fkey foreign KEY (entrada_id) references entrada (id) on delete CASCADE,
  constraint entradaitens_produto_id_fkey foreign KEY (produto_id) references produto (id)
) TABLESPACE pg_default;

create table public.favorito (
  id bigint generated always as identity not null,
  cliente_id integer not null,
  produto_id integer not null,
  created_at timestamp with time zone null default now(),
  constraint favorito_pkey primary key (id),
  constraint favorito_cliente_id_produto_id_key unique (cliente_id, produto_id),
  constraint favorito_cliente_id_fkey foreign KEY (cliente_id) references cliente (id),
  constraint favorito_produto_id_fkey foreign KEY (produto_id) references produto (id)
) TABLESPACE pg_default;

create table public.fornecedor (
  id integer generated always as identity not null,
  cpfcnpj character varying not null,
  nomerazaosocial text not null,
  nomefantasia character varying null,
  endereco character varying null,
  cidade character varying null,
  estado character varying null,
  cep character varying null,
  contato character varying null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  endereconumero text null,
  enderecocomplemento text null,
  bairro text null,
  ativo boolean not null default true,
  codigomunicipio text null,
  constraint fornecedor_pkey primary key (id),
  constraint fornecedor_cnpj_key unique (cpfcnpj)
) TABLESPACE pg_default;

create table public.fornecedorprodutos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  fornecedorid integer not null,
  produtoid integer not null,
  codigofornecedor text not null,
  ultimovalordecompra numeric null,
  constraint fornecedorprodutos_pkey primary key (id),
  constraint fornecedorprodutos_fornecedorid_fkey foreign KEY (fornecedorid) references fornecedor (id),
  constraint fornecedorprodutos_produtoid_fkey foreign KEY (produtoid) references produto (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.imagemvistoria (
  id integer generated always as identity not null,
  checklistid integer not null,
  url character varying not null,
  descricao character varying null,
  createdat timestamp without time zone null default now(),
  constraint imagemvistoria_pkey primary key (id),
  constraint fk_imagem_vistoria_checklist foreign KEY (checklistid) references checklist (id)
) TABLESPACE pg_default;

create table public.item_pedido (
  id bigint generated always as identity not null,
  pedido_id bigint not null,
  produto_id integer not null,
  quantidade integer not null,
  preco_unitario numeric(10, 2) not null,
  constraint item_pedido_pkey primary key (id),
  constraint item_pedido_pedido_id_fkey foreign KEY (pedido_id) references pedido (id),
  constraint item_pedido_produto_id_fkey foreign KEY (produto_id) references produto (id)
) TABLESPACE pg_default;

create table public.nfe (
  id bigserial not null,
  modelo public.enum_modelo_nfe not null default 'NFE'::enum_modelo_nfe,
  serie integer not null,
  numero integer not null,
  chave_acesso character(44) not null,
  ambiente public.enum_ambiente_nfe not null default 'HOMOLOGACAO'::enum_ambiente_nfe,
  status public.enum_status_nfe not null default 'RASCUNHO'::enum_status_nfe,
  ordemservicoid integer null,
  vendaid integer null,
  clienteid integer null,
  dataemissao timestamp with time zone not null,
  dataautorizacao timestamp with time zone null,
  protocolo text null,
  total_produtos numeric(14, 2) not null default 0,
  total_servicos numeric(14, 2) not null default 0,
  total_nfe numeric(14, 2) not null default 0,
  xml_assinado text null,
  xml_autorizado text null,
  justificativacancelamento text null,
  createdat timestamp with time zone not null default now(),
  updatedat timestamp with time zone not null default now(),
  empresaid integer not null,
  icms text null,
  cfop text null,
  created_by uuid null,
  updated_by uuid null,
  deleted_by uuid null,
  is_deleted boolean not null default false,
  deleted_at timestamp with time zone null,
  fornecedorid integer null,
  entradaid bigint null,
  "tpNF" smallint null,
  constraint nfe_pkey primary key (id),
  constraint nfe_chave_acesso_key unique (chave_acesso),
  constraint nfe_created_by_fkey foreign KEY (created_by) references usuario (id),
  constraint nfe_deleted_by_fkey foreign KEY (deleted_by) references usuario (id),
  constraint nfe_empresaid_fkey foreign KEY (empresaid) references empresa (id),
  constraint nfe_entradaid_fkey foreign KEY (entradaid) references entrada (id),
  constraint nfe_fornecedorid_fkey foreign KEY (fornecedorid) references fornecedor (id),
  constraint nfe_ordemservicoid_fkey foreign KEY (ordemservicoid) references ordemservico (id) on delete set null,
  constraint nfe_updated_by_fkey foreign KEY (updated_by) references usuario (id),
  constraint nfe_vendaid_fkey foreign KEY (vendaid) references venda (id) on delete set null,
  constraint nfe_clienteid_fkey foreign KEY (clienteid) references cliente (id),
  constraint ck_nfe_destinatario check (
    (
      (
        (clienteid is not null)
        and (fornecedorid is null)
      )
      or (
        (clienteid is null)
        and (fornecedorid is not null)
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_nfe_cliente on public.nfe using btree (clienteid) TABLESPACE pg_default;

create index IF not exists idx_nfe_ordemservico on public.nfe using btree (ordemservicoid) TABLESPACE pg_default;

create index IF not exists idx_nfe_status on public.nfe using btree (status) TABLESPACE pg_default;

create index IF not exists idx_nfe_venda on public.nfe using btree (vendaid) TABLESPACE pg_default;

create table public.nfe_config (
  id bigserial not null,
  empresaid bigint not null,
  modelo public.enum_modelo_nfe not null default 'NFE'::enum_modelo_nfe,
  serie integer not null default 1,
  ultimo_numero integer not null default 0,
  ambiente public.enum_ambiente_nfe not null default 'HOMOLOGACAO'::enum_ambiente_nfe,
  tp_emis smallint not null default 1,
  versao_layout character varying(5) not null default '4.00'::character varying,
  tipo_impressao_danfe smallint not null default 1,
  permitir_homologacao boolean not null default true,
  permitir_producao boolean not null default true,
  createdat timestamp with time zone not null default now(),
  updatedat timestamp with time zone not null default now(),
  constraint nfe_config_pkey primary key (id),
  constraint nfe_config_empresaid_key unique (empresaid),
  constraint nfe_config_empresaid_fkey foreign KEY (empresaid) references empresa (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.nfe_item (
  id bigserial not null,
  nfe_id bigint not null,
  n_item integer not null,
  produtoid integer null,
  descricao text not null,
  ncm text null,
  cfop text not null,
  csosn text null,
  cest text null,
  unidade public.unidade_medida not null,
  quantidade numeric(14, 4) not null,
  valor_unitario numeric(14, 10) not null,
  valor_total numeric(14, 2) not null,
  valor_desconto numeric(14, 2) null,
  aliquotaicms numeric(5, 2) null,
  valor_bc_icms numeric(14, 2) null,
  valor_icms numeric(14, 2) null,
  cst_pis text null,
  aliquota_pis numeric(5, 2) null,
  valor_pis numeric(14, 2) null,
  cst_cofins text null,
  aliquota_cofins numeric(5, 2) null,
  valor_cofins numeric(14, 2) null,
  createdat timestamp with time zone not null default now(),
  updatedat timestamp with time zone not null default now(),
  cst text null,
  constraint nfe_item_pkey primary key (id),
  constraint nfe_item_nfe_id_fkey foreign KEY (nfe_id) references nfe (id) on delete CASCADE,
  constraint nfe_item_produtoid_fkey foreign KEY (produtoid) references produto (id)
) TABLESPACE pg_default;

create index IF not exists idx_nfe_item_nfe on public.nfe_item using btree (nfe_id) TABLESPACE pg_default;

create index IF not exists idx_nfe_item_produto on public.nfe_item using btree (produtoid) TABLESPACE pg_default;

create table public.nfse_config (
  empresa_id integer not null,
  provedor text null,
  inscricao_municipal text null,
  serie_rps text null,
  usuario text null,
  senha text null,
  token text null,
  certificado_a1_base64 text null,
  senha_certificado text null,
  updated_at timestamp with time zone null default now(),
  constraint nfse_config_pkey primary key (empresa_id),
  constraint nfse_config_empresa_id_fkey foreign KEY (empresa_id) references empresa (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.notafiscal (
  id integer generated always as identity not null,
  ordemservicoid integer null,
  vendaonlineid integer null,
  tipo character varying not null,
  numero character varying not null,
  serie character varying not null,
  dataemissao timestamp without time zone null default now(),
  xml character varying null,
  protocolo character varying null,
  status character varying not null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  constraint notafiscal_pkey primary key (id),
  constraint fk_nota_fiscal_ordem_servico foreign KEY (ordemservicoid) references ordemservico (id),
  constraint fk_nota_fiscal_venda_online foreign KEY (vendaonlineid) references venda (id)
) TABLESPACE pg_default;

create table public.ordemservico (
  id integer generated always as identity not null,
  clienteid integer not null,
  veiculoid integer null,
  usuariocriadorid uuid not null,
  setorid integer null,
  status public.enum_status_os null default 'AGUARDANDO_CHECKLIST'::enum_status_os,
  statusaprovacao public.enum_status_aprovacao null default 'PENDENTE'::enum_status_aprovacao,
  descricao character varying null,
  dataentrada timestamp without time zone null default now(),
  datasaida timestamp without time zone null,
  orcamentototal numeric not null default '0'::numeric,
  observacoes character varying null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  checklist_modelo_id integer null,
  prioridade public.enum_prioridade_os not null default 'NORMAL'::enum_prioridade_os,
  alvo_tipo public.enum_alvo_reparo not null default 'VEICULO'::enum_alvo_reparo,
  pecaid integer null,
  execucao_inicio_em timestamp with time zone null,
  execucao_fim_em timestamp with time zone null,
  created_by uuid null,
  updated_by uuid null,
  deleted_at timestamp with time zone null,
  deleted_by uuid null,
  is_deleted boolean not null default false,
  motivo_cancelamento text null,
  motivo_sem_cobranca text null,
  constraint ordemservico_pkey primary key (id),
  constraint fk_ordem_servico_setor foreign KEY (setorid) references setor (id),
  constraint fk_ordem_servico_usuario foreign KEY (usuariocriadorid) references usuario (id),
  constraint fk_ordem_servico_veiculo foreign KEY (veiculoid) references veiculo (id) on delete CASCADE,
  constraint ordemservico_checklist_modelo_id_fkey foreign KEY (checklist_modelo_id) references checklist_modelo (id),
  constraint ordemservico_created_by_fkey foreign KEY (created_by) references usuario (id),
  constraint ordemservico_deleted_by_fkey foreign KEY (deleted_by) references usuario (id),
  constraint ordemservico_pecaid_fkey foreign KEY (pecaid) references peca (id),
  constraint ordemservico_updated_by_fkey foreign KEY (updated_by) references usuario (id),
  constraint fk_ordem_servico_cliente foreign KEY (clienteid) references cliente (id),
  constraint ordemservico_alvo_consistente check (
    (
      (
        (alvo_tipo = 'VEICULO'::enum_alvo_reparo)
        and (veiculoid is not null)
        and (pecaid is null)
      )
      or (
        (alvo_tipo = 'PECA'::enum_alvo_reparo)
        and (pecaid is not null)
        and (veiculoid is null)
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_ordemservico_clienteid on public.ordemservico using btree (clienteid) TABLESPACE pg_default;

create index IF not exists idx_ordemservico_setorid on public.ordemservico using btree (setorid) TABLESPACE pg_default;

create index IF not exists idx_os_cliente on public.ordemservico using btree (clienteid) TABLESPACE pg_default;

create index IF not exists idx_os_status on public.ordemservico using btree (status) TABLESPACE pg_default;

create trigger ordemservico_status_estorno
after
update OF status on ordemservico for EACH row
execute FUNCTION trg_os_status_estornar ();

create trigger trg_os_execucao_set_times BEFORE
update OF status on ordemservico for EACH row
execute FUNCTION fn_os_execucao_set_times ();

create table public.osaprovacao (
  id bigserial not null,
  ordemservicoid integer not null,
  token uuid not null,
  expira_em timestamp with time zone null,
  usado_em timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  origem text null,
  resultado text null,
  aprovador_doc text null,
  aprovador_usuario_id uuid null,
  constraint osaprovacao_pkey primary key (id),
  constraint osaprovacao_token_key unique (token),
  constraint osaprovacao_aprovador_usuario_id_fkey foreign KEY (aprovador_usuario_id) references usuario (id),
  constraint osaprovacao_ordemservicoid_fkey foreign KEY (ordemservicoid) references ordemservico (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists osaprovacao_ordem_idx on public.osaprovacao using btree (ordemservicoid) TABLESPACE pg_default;

create table public.osproduto (
  ordemservicoid integer not null,
  produtoid integer not null,
  quantidade integer null default 1,
  precounitario numeric not null,
  subtotal numeric not null,
  constraint osproduto_pkey primary key (ordemservicoid, produtoid),
  constraint fk_os_produto_produto foreign KEY (produtoid) references produto (id),
  constraint osproduto_ordemservicoid_fkey foreign KEY (ordemservicoid) references ordemservico (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.osproduto_baixa (
  ordemservicoid integer not null,
  produtoid integer not null,
  quantidade integer not null default 0,
  constraint osproduto_baixa_pkey primary key (ordemservicoid, produtoid),
  constraint osproduto_baixa_ordemservicoid_fkey foreign KEY (ordemservicoid) references ordemservico (id) on delete CASCADE,
  constraint osproduto_baixa_produtoid_fkey foreign KEY (produtoid) references produto (id)
) TABLESPACE pg_default;

create table public.osservico (
  ordemservicoid integer not null,
  servicoid integer not null,
  quantidade integer null default 1,
  precounitario numeric not null,
  subtotal numeric not null,
  constraint osservico_pkey primary key (ordemservicoid, servicoid),
  constraint fk_os_servico_servico foreign KEY (servicoid) references servico (id),
  constraint osservico_ordemservicoid_fkey foreign KEY (ordemservicoid) references ordemservico (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger trg_recalc_osservico_subtotal
after
update OF subtotal on osservico for EACH row
execute FUNCTION tg_recalc_comissao_osservico_on_subtotal ();

create table public.osservico_realizador (
  ordemservicoid integer not null,
  servicoid integer not null,
  usuarioid uuid not null,
  comissao_percent_aplicada numeric(5, 2) null,
  createdat timestamp with time zone not null default now(),
  valor_base numeric(12, 2) null,
  valor_comissao numeric(12, 2) null,
  updated_at timestamp with time zone not null default now(),
  constraint osservico_realizador_pkey primary key (ordemservicoid, servicoid, usuarioid),
  constraint fk_or_osservico foreign KEY (ordemservicoid, servicoid) references osservico (ordemservicoid, servicoid) on delete CASCADE,
  constraint fk_or_usuario foreign KEY (usuarioid) references usuario (id) on update CASCADE
) TABLESPACE pg_default;

create trigger trg_recalc_or_del
after DELETE on osservico_realizador for EACH row
execute FUNCTION tg_recalc_comissao_osservico_realizador ();

create trigger trg_recalc_or_ins
after INSERT on osservico_realizador for EACH row
execute FUNCTION tg_recalc_comissao_osservico_realizador ();

create trigger trg_set_or_percent_before_ins BEFORE INSERT on osservico_realizador for EACH row
execute FUNCTION tg_set_comissao_percent_aplicada ();

create table public.pagamento (
  id bigserial not null,
  ordemservicoid integer not null,
  metodo text not null,
  valor numeric not null,
  status text not null default 'CRIADO'::text,
  provider_tx_id text null,
  nsu text null,
  autorizacao text null,
  bandeira text null,
  parcelas integer null default 1,
  comprovante text null,
  criado_em timestamp with time zone null default now(),
  atualizado_em timestamp with time zone null default now(),
  constraint pagamento_pkey primary key (id),
  constraint pagamento_ordemservicoid_fkey foreign KEY (ordemservicoid) references ordemservico (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.pagamento_config (
  empresa_id integer not null,
  provider_cartao text null default 'stone'::text,
  cartao_merchant_id text null,
  cartao_api_key text null,
  cartao_webhook_url text null,
  cartao_parcelas_max integer null default 1,
  cartao_captura_auto boolean null default true,
  cartao_terminal_ids text[] null default '{}'::text[],
  pix_provider text null default 'stone'::text,
  pix_chave text null,
  pix_client_id text null,
  pix_client_secret text null,
  pix_webhook_url text null,
  pix_expiracao_s integer null default 1800,
  dinheiro_habilitado boolean null default true,
  updated_at timestamp with time zone null default now(),
  constraint pagamento_config_pkey primary key (empresa_id),
  constraint pagamento_config_empresa_id_fkey foreign KEY (empresa_id) references empresa (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.pagamento_evento (
  id bigserial not null,
  pagamentoid bigint not null,
  tipo text not null,
  payload jsonb null,
  criado_em timestamp with time zone null default now(),
  constraint pagamento_evento_pkey primary key (id),
  constraint pagamento_evento_pagamentoid_fkey foreign KEY (pagamentoid) references pagamento (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.peca (
  id integer generated always as identity not null,
  clienteid integer not null,
  veiculoid integer null,
  titulo text not null,
  descricao text null,
  fabricante text null,
  modelo text null,
  lacre text null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  constraint peca_pkey primary key (id),
  constraint peca_clienteid_fkey foreign KEY (clienteid) references cliente (id),
  constraint peca_veiculoid_fkey foreign KEY (veiculoid) references veiculo (id)
) TABLESPACE pg_default;

create table public.pedido (
  id bigint generated always as identity not null,
  cliente_id integer not null,
  status text not null default 'PENDENTE'::text,
  total numeric(10, 2) not null,
  data_pedido timestamp with time zone null default now(),
  forma_pagamento text null,
  endereco_entrega_snapshot jsonb null,
  constraint pedido_pkey primary key (id),
  constraint pedido_cliente_id_fkey foreign KEY (cliente_id) references cliente (id)
) TABLESPACE pg_default;

create table public.perfil (
  id integer generated always as identity not null,
  nome character varying not null,
  descricao character varying null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  constraint perfil_pkey primary key (id),
  constraint perfil_nome_key unique (nome)
) TABLESPACE pg_default;

create table public.perfilpermissao (
  perfilid integer not null,
  permissaoid integer not null,
  createdat timestamp without time zone null default now(),
  constraint perfilpermissao_pkey primary key (perfilid, permissaoid),
  constraint perfilpermissao_perfil_fkey foreign KEY (perfilid) references perfil (id),
  constraint perfilpermissao_permissao_fkey foreign KEY (permissaoid) references permissao (id)
) TABLESPACE pg_default;

create table public.permissao (
  id integer generated always as identity not null,
  nome character varying not null,
  descricao character varying null,
  constraint permissao_pkey primary key (id),
  constraint permissao_nome_key unique (nome)
) TABLESPACE pg_default;

create table public.produto (
  id integer generated always as identity not null,
  descricao text null,
  precovenda numeric not null,
  estoque integer not null default 0,
  estoqueminimo integer not null default 0,
  ncm text null,
  unidade public.unidade_medida not null default 'UN'::unidade_medida,
  cest text null,
  csosn text null,
  codigobarras text null,
  createdat timestamp with time zone null default now(),
  updatedat timestamp with time zone null default now(),
  referencia text null,
  titulo text not null,
  status_estoque public.estoque_status not null default 'OK'::estoque_status,
  fabricante text null,
  grupo public.grupo_produto null default 'OUTROS'::grupo_produto,
  "exibirPdv" boolean not null default false,
  "tituloMarketplace" text not null default ''::text,
  "descricaoMarketplace" text not null default ''::text,
  "cClassTrib" text null,
  "cstIbs" text null,
  "cstCbs" text null,
  cst text null,
  aliquotaicms numeric null,
  cfop text null,
  cst_pis text null,
  aliquota_pis numeric(5, 2) null,
  cst_cofins text null,
  aliquota_cofins numeric(5, 2) null,
  "imgUrl" text null,
  updated_by uuid null,
  created_by uuid null,
  is_deleted boolean not null default false,
  deleted_at timestamp with time zone null,
  deleted_by uuid null,
  grupo_produto_id integer not null default 1,
  tipo_unidade_id integer not null default 1,
  precocompra numeric null,
  constraint produto_pkey primary key (id),
  constraint produto_created_by_fkey foreign KEY (created_by) references usuario (id),
  constraint produto_deleted_by_fkey foreign KEY (deleted_by) references usuario (id),
  constraint produto_grupo_produto_id_fkey foreign KEY (grupo_produto_id) references produtogrupo (id) on update CASCADE,
  constraint produto_tipo_unidade_id_fkey foreign KEY (tipo_unidade_id) references unidademedida (id) on update CASCADE,
  constraint produto_updated_by_fkey foreign KEY (updated_by) references usuario (id)
) TABLESPACE pg_default;

create trigger trg_fill_titulo_marketplace BEFORE INSERT
or
update OF "tituloMarketplace",
titulo on produto for EACH row
execute FUNCTION fn_fill_titulo_marketplace ();

create trigger trg_set_status_estoque BEFORE INSERT
or
update OF estoque,
estoqueminimo on produto for EACH row
execute FUNCTION fn_set_status_estoque ();

create table public.produto_imagem (
  id bigint generated always as identity not null,
  produto_id integer not null,
  url text not null,
  path text not null,
  ordem integer not null default 0,
  createdat timestamp with time zone not null default now(),
  constraint produto_imagem_pkey primary key (id),
  constraint produto_imagem_produto_id_fkey foreign KEY (produto_id) references produto (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists produto_imagem_produto_id_idx on public.produto_imagem using btree (produto_id) TABLESPACE pg_default;

create unique INDEX IF not exists produto_imagem_produto_path_uq on public.produto_imagem using btree (path) TABLESPACE pg_default;

create table public.produtogrupo (
  id integer generated always as identity not null,
  nome text not null,
  descricao text null,
  ativo boolean not null default true,
  createdat timestamp without time zone not null default now(),
  updatedat timestamp without time zone not null default now(),
  constraint produtogrupo_pkey primary key (id)
) TABLESPACE pg_default;

create table public.servico (
  id integer generated always as identity not null,
  codigo character varying not null,
  descricao character varying not null,
  precohora numeric not null,
  codigoservicomunicipal character varying null,
  aliquotaiss numeric null,
  cnae character varying null,
  itemlistaservico character varying null,
  tiposervicoid integer null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  ativo boolean null default true,
  constraint servico_pkey primary key (id),
  constraint servico_codigo_key unique (codigo),
  constraint fk_servico_tipo_servico foreign KEY (tiposervicoid) references tiposervico (id)
) TABLESPACE pg_default;

create table public.setor (
  id integer generated always as identity not null,
  nome character varying not null,
  descricao character varying null,
  responsavel text null,
  ativo boolean not null default true,
  constraint setor_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tiposervico (
  id integer generated always as identity not null,
  nome character varying not null,
  descricao character varying null,
  categoriaid integer not null,
  constraint tiposervico_pkey primary key (id),
  constraint fk_tipo_servico_categoria foreign KEY (categoriaid) references categoriaservico (id)
) TABLESPACE pg_default;

create table public.transacao (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  descricao text not null,
  valor numeric(14, 2) not null,
  data timestamp with time zone not null,
  metodopagamento public.metodo_pagamento not null,
  categoria text not null default 'NÃO RELACIONADO'::text,
  tipo public.tipos_transacao not null,
  cliente_id integer null,
  banco_id bigint not null,
  nomepagador text not null,
  cpfcnpjpagador text not null,
  ordemservicoid integer null,
  "valorLiquido" numeric null,
  vendaid integer null,
  pendente boolean not null default false,
  created_by uuid null,
  updated_by uuid null,
  is_deleted boolean not null default false,
  deleted_at timestamp with time zone null,
  deleted_by uuid null,
  constraint transacao_pkey primary key (id),
  constraint transacao_cliente_id_fkey foreign KEY (cliente_id) references cliente (id) on update CASCADE,
  constraint transacao_created_by_fkey foreign KEY (created_by) references usuario (id),
  constraint transacao_deleted_by_fkey foreign KEY (deleted_by) references usuario (id),
  constraint transacao_ordemservicoid_fkey foreign KEY (ordemservicoid) references ordemservico (id) on delete CASCADE,
  constraint transacao_updated_by_fkey foreign KEY (updated_by) references usuario (id),
  constraint transacao_banco_id_fkey foreign KEY (banco_id) references bancoconta (id) on update RESTRICT,
  constraint transacao_vendaid_fkey foreign KEY (vendaid) references venda (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_transacao_ordemservicoid on public.transacao using btree (ordemservicoid) TABLESPACE pg_default;

create table public.transferencias_veiculos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  veiculo_id integer null,
  dono_anteior integer null,
  novo_dono integer null,
  created_by uuid null,
  constraint transferencias_veiculos_pkey primary key (id),
  constraint transferencias_veiculos_created_by_fkey foreign KEY (created_by) references usuario (id),
  constraint transferencias_veiculos_dono_anteior_fkey foreign KEY (dono_anteior) references cliente (id),
  constraint transferencias_veiculos_novo_dono_fkey foreign KEY (novo_dono) references cliente (id),
  constraint transferencias_veiculos_veiculo_id_fkey foreign KEY (veiculo_id) references veiculo (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.unidademedida (
  id integer generated always as identity not null,
  sigla character varying not null,
  descricao text null,
  ativo boolean not null default true,
  createdat timestamp without time zone not null default now(),
  updatedat timestamp without time zone not null default now(),
  constraint unidademedida_pkey primary key (id),
  constraint unidademedida_sigla_key unique (sigla)
) TABLESPACE pg_default;

create table public.usuario (
  id uuid not null default gen_random_uuid (),
  email character varying not null,
  nome character varying not null,
  setorid integer null,
  perfilid integer null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  ativo boolean not null default true,
  salario numeric(12, 2) null,
  comissao_percent numeric(5, 2) null,
  data_admissao date null,
  data_demissao date null,
  is_root boolean not null default false,
  constraint usuario_pkey primary key (id),
  constraint usuario_email_key unique (email),
  constraint usuario_auth_fkey foreign KEY (id) references auth.users (id) on delete CASCADE,
  constraint usuario_perfilid_fkey foreign KEY (perfilid) references perfil (id),
  constraint usuario_setorid_fkey foreign KEY (setorid) references setor (id)
) TABLESPACE pg_default;

create index IF not exists idx_usuario_email on public.usuario using btree (email) TABLESPACE pg_default;

create table public.veiculo (
  id integer generated always as identity not null,
  clienteid integer not null,
  placa character varying not null,
  modelo text not null,
  marca text not null,
  ano integer null,
  cor character varying null,
  kmatual integer null,
  createdat timestamp without time zone null default now(),
  updatedat timestamp without time zone null default now(),
  placa_formatada text GENERATED ALWAYS as (to_mercosul_equivalente ((placa)::text)) STORED not null,
  tipo public.tipo_veiculo not null default 'CARROS'::tipo_veiculo,
  constraint veiculo_pkey primary key (id),
  constraint veiculo_placa_formatada_key unique (placa_formatada),
  constraint veiculo_placa_key unique (placa),
  constraint fk_veiculo_cliente foreign KEY (clienteid) references cliente (id) on delete CASCADE,
  constraint veiculo_placa_formato_chk check (
    (
      ((placa)::text ~ '^[A-Z]{3}[0-9]{4}$'::text)
      or (
        (placa)::text ~ '^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$'::text
      )
    )
  )
) TABLESPACE pg_default;

create trigger trg_normalize_placa_veiculo BEFORE INSERT
or
update OF placa on veiculo for EACH row
execute FUNCTION normalize_placa ();

create table public.venda (
  id integer generated always as identity not null,
  clienteid integer not null,
  status public.enum_status_venda not null,
  valortotal numeric not null,
  datavenda timestamp with time zone null,
  createdat timestamp with time zone null,
  updatedat timestamp with time zone null,
  created_by uuid null,
  desconto_tipo public.enum_tipo_desconto_venda null,
  desconto_valor numeric null,
  sub_total numeric not null,
  canal public.enum_canal_venda not null default 'PDV'::enum_canal_venda,
  endereco_entrega_snapshot jsonb null,
  forma_pagamento text null,
  constraint vendaonline_pkey primary key (id),
  constraint fk_venda_online_cliente foreign KEY (clienteid) references cliente (id),
  constraint venda_created_by_fkey foreign KEY (created_by) references usuario (id)
) TABLESPACE pg_default;

create table public.vendaproduto (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  venda_id integer not null,
  produtoid integer not null,
  sub_total numeric not null,
  valor_total numeric not null,
  valor_desconto numeric null,
  tipo_desconto public.enum_tipo_desconto_venda null,
  quantidade integer not null,
  constraint vendaproduto_pkey primary key (id),
  constraint vendaproduto_produtoid_fkey foreign KEY (produtoid) references produto (id),
  constraint vendaproduto_venda_id_fkey foreign KEY (venda_id) references venda (id) on delete CASCADE
) TABLESPACE pg_default;

-- FUNCTIONS --

atualizar_totais_nfe
  update nfe
  set
    total_produtos = coalesce((
      select sum(ni.valor_total)
      from nfe_item ni
      where ni.nfe_id = nfe.id
    ), 0),
    total_nfe = coalesce((
      select sum(ni.valor_total)
      from nfe_item ni
      where ni.nfe_id = nfe.id
    ), 0),
    updatedat = now()
  where id = p_nfe_id;

  criar_nfe_de_os
  DECLARE
  v_nfe_id      bigint;
  v_numero      int;
  v_serie       int;
  v_modelo      public.enum_modelo_nfe;
  v_ambiente    public.enum_ambiente_nfe;
  v_chave       char(44);
  v_dataemissao timestamptz := now();
  v_cod_uf      text;
  v_cnpj_emit   text;
  v_ano         text;
  v_mes         text;
  v_mod         text;
  v_serie_str   text;
  v_numero_str  text;
  v_tp_emis     text;
  v_cod_nf      text;
  v_cdv         text;

  -- por enquanto fixo; depois você pode amarrar a empresa da OS
  v_empresaid   bigint := 1;

  v_cfg         nfe_config%ROWTYPE;
  v_emp         empresa%ROWTYPE;
BEGIN
  --------------------------------------------------------------------
  -- 1) Validar se a OS existe
  --------------------------------------------------------------------
  IF NOT EXISTS (SELECT 1 FROM ordemservico WHERE id = p_ordemservicoid) THEN
    RAISE EXCEPTION 'OS % não encontrada', p_ordemservicoid;
  END IF;

  --------------------------------------------------------------------
  -- 2) Carregar EMPRESA e NFE_CONFIG da empresa
  --------------------------------------------------------------------
  SELECT *
    INTO v_emp
  FROM empresa
  WHERE id = v_empresaid;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Empresa % não encontrada na tabela EMPRESA', v_empresaid;
  END IF;

  SELECT *
    INTO v_cfg
  FROM nfe_config
  WHERE empresaid = v_empresaid;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Configuração de NF-e (nfe_config) não encontrada para empresa %', v_empresaid;
  END IF;

  --------------------------------------------------------------------
  -- 3) Puxar parâmetros da config
  --------------------------------------------------------------------
  v_modelo   := v_cfg.modelo;
  v_serie    := v_cfg.serie;
  v_ambiente := v_cfg.ambiente;
  v_tp_emis  := v_cfg.tp_emis::text;   -- tp_emis é smallint na config

  -- cUF = 2 primeiros dígitos do código do município
  v_cod_uf := substring(coalesce(v_emp.codigomunicipio, '') FROM 1 FOR 2);

  IF v_cod_uf IS NULL OR length(v_cod_uf) <> 2 THEN
    RAISE EXCEPTION 'Código de município inválido para empresa % (codigomunicipio=%)',
      v_empresaid, v_emp.codigomunicipio;
  END IF;

  -- CNPJ somente números
  v_cnpj_emit := regexp_replace(coalesce(v_emp.cnpj, ''), '\D', '', 'g');

  IF length(v_cnpj_emit) <> 14 THEN
    RAISE EXCEPTION 'CNPJ da empresa % inválido (%). Deve ter 14 dígitos numéricos.',
      v_empresaid, v_emp.cnpj;
  END IF;

  v_ano := to_char(v_dataemissao, 'YY');
  v_mes := to_char(v_dataemissao, 'MM');
  v_mod := '55';  -- NF-e

  --------------------------------------------------------------------
  -- 4) Descobrir próximo número da NF-e a partir do nfe_config
  --    (ultimo_numero + 1)
  --------------------------------------------------------------------
  v_numero := v_cfg.ultimo_numero + 1;

  v_serie_str  := lpad(v_serie::text, 3, '0');
  v_numero_str := lpad(v_numero::text, 9, '0');

  --------------------------------------------------------------------
  -- 5) Gerar cNF (8 dígitos) aleatório
  --------------------------------------------------------------------
  v_cod_nf := lpad((floor(random() * 99999999))::int::text, 8, '0');

  --------------------------------------------------------------------
  -- 6) Montar chave de acesso SEM o DV
  --    cUF(2) + AAMM(4) + CNPJ(14) + mod(2) + série(3)
  --    + nNF(9) + tpEmis(1) + cNF(8)
  --------------------------------------------------------------------
  v_chave :=
    (v_cod_uf || v_ano || v_mes || v_cnpj_emit || v_mod ||
     v_serie_str || v_numero_str || v_tp_emis || v_cod_nf);

  --------------------------------------------------------------------
  -- 7) Calcular dígito verificador (módulo 11)
  --------------------------------------------------------------------
  DECLARE
    soma int := 0;
    peso int := 2;
    i    int;
    dig  int;
    ch_sem_dv text := v_chave;
  BEGIN
    FOR i IN REVERSE length(ch_sem_dv)..1 LOOP
      soma := soma + (substr(ch_sem_dv, i, 1)::int * peso);
      peso := peso + 1;
      IF peso > 9 THEN
        peso := 2;
      END IF;
    END LOOP;

    dig := 11 - (soma % 11);

    -- mantém a mesma regra que você já estava usando
    IF dig = 0 OR dig = 1 THEN
      dig := 0;
    END IF;

    v_cdv := dig::text;
  END;

  v_chave := v_chave || v_cdv;

  --------------------------------------------------------------------
  -- 8) Inserir na tabela NFE (RASCUNHO)
  --------------------------------------------------------------------
  INSERT INTO nfe (
    modelo,
    serie,
    numero,
    chave_acesso,
    ambiente,
    status,
    ordemservicoid,
    vendaid,
    clienteid,
    empresaid,
    dataemissao,
    total_produtos,
    total_servicos,
    total_nfe,
    xml_assinado,
    xml_autorizado
  )
  SELECT
    v_modelo,
    v_serie,
    v_numero,
    v_chave,
    v_ambiente,
    'RASCUNHO',
    os.id,
    NULL,
    os.clienteid,
    v_empresaid,          -- antes era 3 fixo
    v_dataemissao,
    0,
    0,
    0,
    NULL,
    NULL
  FROM ordemservico os
  WHERE os.id = p_ordemservicoid
  RETURNING id INTO v_nfe_id;

  --------------------------------------------------------------------
  -- 9) Atualizar nfe_config.ultimo_numero
  --------------------------------------------------------------------
  UPDATE nfe_config
     SET ultimo_numero = v_numero,
         updatedat     = now()
   WHERE id = v_cfg.id;

  RETURN v_nfe_id;
END;

criar_nfe_de_venda
declare
  v_nfe_id      bigint;
  v_numero      int;
  v_serie       int;
  v_modelo      public.enum_modelo_nfe;
  v_ambiente    public.enum_ambiente_nfe;
  v_chave       char(44);
  v_dataemissao timestamptz := now();
  v_cod_uf      text;
  v_cnpj_emit   text;
  v_ano         text;
  v_mes         text;
  v_mod         text;
  v_serie_str   text;
  v_numero_str  text;
  v_tp_emis     text;
  v_cod_nf      text;
  v_cdv         text;

  -- por enquanto fixo; você pode amarrar depois
  v_empresaid   bigint := 1;

  v_cfg         public.nfe_config%rowtype;
  v_emp         public.empresa%rowtype;
  v_venda       public.venda%rowtype;
begin
  -- 1) Validar se a VENDA existe
  select * into v_venda
  from public.venda
  where id = p_vendaid;

  if not found then
    raise exception 'Venda % não encontrada', p_vendaid;
  end if;

  -- 2) Carregar EMPRESA e NFE_CONFIG
  select * into v_emp
  from public.empresa
  where id = v_empresaid;

  if not found then
    raise exception 'Empresa % não encontrada na tabela EMPRESA', v_empresaid;
  end if;

  select * into v_cfg
  from public.nfe_config
  where empresaid = v_empresaid;

  if not found then
    raise exception 'Configuração de NF-e (nfe_config) não encontrada para empresa %', v_empresaid;
  end if;

  -- 3) Puxar parâmetros da config
  v_modelo   := v_cfg.modelo;
  v_serie    := v_cfg.serie;
  v_ambiente := v_cfg.ambiente;
  v_tp_emis  := v_cfg.tp_emis::text;

  -- cUF = 2 primeiros dígitos do código do município
  v_cod_uf := substring(coalesce(v_emp.codigomunicipio, '') from 1 for 2);

  if v_cod_uf is null or length(v_cod_uf) <> 2 then
    raise exception 'Código de município inválido para empresa % (codigomunicipio=%)',
      v_empresaid, v_emp.codigomunicipio;
  end if;

  -- CNPJ somente números
  v_cnpj_emit := regexp_replace(coalesce(v_emp.cnpj, ''), '\D', '', 'g');

  if length(v_cnpj_emit) <> 14 then
    raise exception 'CNPJ da empresa % inválido (%). Deve ter 14 dígitos numéricos.',
      v_empresaid, v_emp.cnpj;
  end if;

  v_ano := to_char(v_dataemissao, 'YY');
  v_mes := to_char(v_dataemissao, 'MM');
  v_mod := '55';

  -- 4) Próximo número (ultimo_numero + 1)
  v_numero := v_cfg.ultimo_numero + 1;

  v_serie_str  := lpad(v_serie::text, 3, '0');
  v_numero_str := lpad(v_numero::text, 9, '0');

  -- 5) cNF (8 dígitos)
  v_cod_nf := lpad((floor(random() * 99999999))::int::text, 8, '0');

  -- 6) chave sem DV
  v_chave :=
    (v_cod_uf || v_ano || v_mes || v_cnpj_emit || v_mod ||
     v_serie_str || v_numero_str || v_tp_emis || v_cod_nf);

  -- 7) DV (módulo 11)
  declare
    soma int := 0;
    peso int := 2;
    i    int;
    dig  int;
    ch_sem_dv text := v_chave;
  begin
    for i in reverse length(ch_sem_dv)..1 loop
      soma := soma + (substr(ch_sem_dv, i, 1)::int * peso);
      peso := peso + 1;
      if peso > 9 then
        peso := 2;
      end if;
    end loop;

    dig := 11 - (soma % 11);

    if dig = 0 or dig = 1 then
      dig := 0;
    end if;

    v_cdv := dig::text;
  end;

  v_chave := v_chave || v_cdv;

  -- 8) Inserir NFE (RASCUNHO) vinculada à VENDA
  insert into public.nfe (
    modelo,
    serie,
    numero,
    chave_acesso,
    ambiente,
    status,
    ordemservicoid,
    vendaid,
    clienteid,
    empresaid,
    dataemissao,
    total_produtos,
    total_servicos,
    total_nfe,
    xml_assinado,
    xml_autorizado
  )
  values (
    v_modelo,
    v_serie,
    v_numero,
    v_chave,
    v_ambiente,
    'RASCUNHO',
    null,
    v_venda.id,
    v_venda.clienteid,
    v_empresaid,
    v_dataemissao,
    0,
    0,
    0,
    null,
    null
  )
  returning id into v_nfe_id;

  -- 9) Atualizar nfe_config.ultimo_numero
  update public.nfe_config
     set ultimo_numero = v_numero,
         updatedat     = now()
   where id = v_cfg.id;

  return v_nfe_id;
end;

estornar_baixa_estoque_os

begin
  -- devolve tudo que foi baixado
  update public.produto p
     set estoque = p.estoque + b.quantidade
    from public.osproduto_baixa b
   where b.ordemservicoid = p_os_id
     and p.id = b.produtoid;

  delete from public.osproduto_baixa
   where ordemservicoid = p_os_id;
end


fn_baixa_estoque_produto
declare
  v_estoque integer;
begin
  -- quantidade inválida: não faz nada
  if p_quantidade is null or p_quantidade <= 0 then
    return;
  end if;

  -- trava a linha para evitar corrida de concorrência
  select estoque
    into v_estoque
  from produto
  where id = p_produto_id
  for update;

  if v_estoque is null then
    raise exception 'Produto % não encontrado para baixa de estoque.', p_produto_id
      using errcode = 'P0001';
  end if;

  if v_estoque < p_quantidade then
    raise exception 'Estoque insuficiente para produto %, em estoque: %, necessário: %',
      p_produto_id, v_estoque, p_quantidade
      using errcode = 'P0001';
  end if;

  update produto
    set estoque = estoque - p_quantidade,
        updatedat = now()
  where id = p_produto_id;
end;


fn_criar_venda_com_itens
declare
  v_cliente_id integer;
  v_created_by uuid;
  v_status public.enum_status_venda;
  v_desconto_tipo public.enum_tipo_desconto_venda;
  v_desconto_valor numeric;
  v_sub_total numeric;
  v_valor_total numeric;
  v_data_venda timestamp; -- ou timestamptz se sua coluna for assim

  v_venda_id integer;

  v_itens jsonb;
  v_item jsonb;
  v_produto_id integer;
  v_quantidade integer;
  v_item_sub_total numeric;
  v_item_valor_total numeric;
  v_item_valor_desconto numeric;
  v_item_tipo_desconto public.enum_tipo_desconto_venda;
begin
  -- Campos obrigatórios
  v_cliente_id := (p_venda->>'clienteId')::integer;
  v_created_by := (p_venda->>'created_by')::uuid;
  v_status := (p_venda->>'status')::public.enum_status_venda;
  v_sub_total := (p_venda->>'subTotal')::numeric;
  v_valor_total := (p_venda->>'valorTotal')::numeric;
  v_data_venda := nullif(p_venda->>'dataVenda', '')::timestamp;

  if v_cliente_id is null
     or v_created_by is null
     or v_status is null
     or v_sub_total is null
     or v_valor_total is null then
    raise exception 'Campos obrigatórios ausentes em p_venda (clienteId, created_by, status, subTotal, valorTotal).'
      using errcode = 'P0001';
  end if;

  -- Campos opcionais
  if p_venda ? 'descontoTipo' then
    v_desconto_tipo := nullif(p_venda->>'descontoTipo', '')::public.enum_tipo_desconto_venda;
  end if;

  if p_venda ? 'descontoValor' then
    v_desconto_valor := nullif(p_venda->>'descontoValor', '')::numeric;
  end if;

  -- Itens
  v_itens := p_venda->'itens';

  if v_itens is null or jsonb_typeof(v_itens) <> 'array' then
    raise exception 'p_venda.itens deve ser um array JSON.'
      using errcode = 'P0001';
  end if;

  if jsonb_array_length(v_itens) = 0 then
    raise exception 'p_venda.itens não pode ser vazio.'
      using errcode = 'P0001';
  end if;

  -- 1) Para cada item: validação básica + baixa de estoque (chamada à fn_baixa_estoque_produto)
  for v_item in
    select value
    from jsonb_array_elements(v_itens) as t(value)
  loop
    v_produto_id := (v_item->>'produtoId')::integer;
    v_quantidade := (v_item->>'quantidade')::integer;

    if v_produto_id is null or v_quantidade is null or v_quantidade <= 0 then
      raise exception 'Cada item deve possuir produtoId e quantidade > 0.'
        using errcode = 'P0001';
    end if;

    -- Dá baixa no estoque (valida e atualiza)
    perform public.fn_baixa_estoque_produto(v_produto_id, v_quantidade);
  end loop;

  -- 2) Cria a venda
  insert into public.venda (
    clienteid,
    created_by,
    status,
    sub_total,
    valortotal,
    desconto_tipo,
    desconto_valor,
    datavenda
  ) values (
    v_cliente_id,
    v_created_by,
    v_status,
    v_sub_total,
    v_valor_total,
    v_desconto_tipo,
    v_desconto_valor,
    coalesce(v_data_venda, now())
  )
  returning id into v_venda_id;

  -- 3) Cria os itens (vendaproduto)
  for v_item in
    select value
    from jsonb_array_elements(v_itens) as t(value)
  loop
    v_produto_id := (v_item->>'produtoId')::integer;
    v_quantidade := (v_item->>'quantidade')::integer;
    v_item_sub_total := (v_item->>'subTotal')::numeric;
    v_item_valor_total := (v_item->>'valorTotal')::numeric;

    if v_item->>'valorDesconto' is not null then
      v_item_valor_desconto := (v_item->>'valorDesconto')::numeric;
    else
      v_item_valor_desconto := null;
    end if;

    if v_item->>'tipoDesconto' is not null then
      v_item_tipo_desconto := (v_item->>'tipoDesconto')::public.enum_tipo_desconto_venda;
    else
      v_item_tipo_desconto := null;
    end if;

    insert into public.vendaproduto (
      venda_id,
      produtoid,
      quantidade,
      sub_total,
      valor_total,
      valor_desconto,
      tipo_desconto
    ) values (
      v_venda_id,
      v_produto_id,
      v_quantidade,
      v_item_sub_total,
      v_item_valor_total,
      v_item_valor_desconto,
      v_item_tipo_desconto
    );
  end loop;

  return v_venda_id;
end;

fn_fill_titulo_marketplace
begin
  if new."tituloMarketplace" is null
     or btrim(new."tituloMarketplace") = '' then
    new."tituloMarketplace" := new.titulo;
  end if;

  return new;
end;

fn_os_execucao_set_times

begin
  -- Quando entra em EM_ANDAMENTO, marca início (só se ainda não tiver)
  if (new.status::text = 'EM_ANDAMENTO' and old.status is distinct from new.status) then
    new.execucao_inicio_em := coalesce(old.execucao_inicio_em, now());
    new.execucao_fim_em := null; -- se voltar para andamento, reabre a execução
  end if;

  -- Quando entra em PAGAMENTO, marca fim (só se tiver início e ainda não tiver fim)
  if (new.status::text = 'PAGAMENTO' and old.status is distinct from new.status) then
    if (old.execucao_inicio_em is not null) then
      new.execucao_inicio_em := old.execucao_inicio_em;
      new.execucao_fim_em := coalesce(old.execucao_fim_em, now());
    end if;
  end if;

  return new;
end;


fn_set_status_estoque
begin
  new.status_estoque :=
    case
      when new.estoque <= 0 then 'SEM_ESTOQUE'
      when new.estoque <= (new.estoqueminimo / 2) then 'CRITICO'
      when new.estoque <= new.estoqueminimo then 'BAIXO'
      else 'OK'
    end;
  return new;
end;

fn_set_titulo_marketplace_product
begin
  new.tituloMarketplace :=
    case
      when new.tituloMarketplace = '' then new.titulo
    end;
  return new;
end;

handle_new_auth_user
begin
  insert into public.usuario (id, email, nome, perfilid, setorid, createdat, updatedat)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'nome', new.email),
    nullif(new.raw_user_meta_data->>'perfilid','')::int,
    nullif(new.raw_user_meta_data->>'setorid','')::int,
    now(),
    now()
  )
  on conflict (id) do update
    set email     = excluded.email,
        nome      = coalesce(excluded.nome, public.usuario.nome),
        perfilid  = coalesce(excluded.perfilid, public.usuario.perfilid),
        setorid   = coalesce(excluded.setorid, public.usuario.setorid),
        updatedat = now();

  return new;
end;

handle_update_auth_user_email

begin
  if new.email is distinct from old.email then
    update public.usuario
       set email = new.email,
           updatedat = now()
     where id = new.id;
  end if;
  return new;
end;


is_staff

  select exists (
    select 1 from public.usuario u
    where u.id = (select auth.uid())
      and u.ativo = true
  );


normalize_placa

begin
  new.placa := upper(regexp_replace(new.placa, '[^A-Za-z0-9]', '', 'g'));
  return new;
end;


preencher_itens_nfe_de_os
declare
  v_nfe record;
begin
  --------------------------------------------------------------------
  -- 1) Verifica se a NF-e existe e está vinculada a uma OS
  --------------------------------------------------------------------
  select *
    into v_nfe
  from nfe
  where id = p_nfe_id;

  if not found then
    raise exception 'NF-e % não encontrada na tabela nfe', p_nfe_id;
  end if;

  if v_nfe.ordemservicoid is null then
    raise exception
      'NF-e % não está vinculada a uma ordem de serviço (ordemservicoid nulo).',
      p_nfe_id;
  end if;

  --------------------------------------------------------------------
  -- 2) Remove itens anteriores da NF-e (se houver) para recriar do zero
  --------------------------------------------------------------------
  delete from nfe_item
  where nfe_id = p_nfe_id;

  --------------------------------------------------------------------
  -- 3) Insere itens da OS (osproduto) na nfe_item,
  --    herdando ICMS, PIS e COFINS do produto.
  --------------------------------------------------------------------
  insert into nfe_item (
    nfe_id,
    n_item,
    produtoid,
    descricao,
    ncm,
    cfop,
    csosn,
    cest,
    unidade,
    quantidade,
    valor_unitario,
    valor_total,
    valor_desconto,
    aliquotaicms,
    valor_bc_icms,
    valor_icms,
    cst_pis,
    aliquota_pis,
    valor_pis,
    cst_cofins,
    aliquota_cofins,
    valor_cofins,
    cst
  )
  select
    n.id as nfe_id,
    row_number() over (order by op.produtoid) as n_item,

    -- identificação do produto
    p.id as produtoid,
    coalesce(p.titulo, p.descricao) as descricao,
    p.ncm,
    coalesce(p.cfop, '5102') as cfop,
    p.csosn,
    p.cest,
    p.unidade,

    -- quantidade e valores
    op.quantidade::numeric(14,4)      as quantidade,
    op.precounitario::numeric(14,10)  as valor_unitario,
    op.subtotal::numeric(14,2)        as valor_total,
    0::numeric(14,2)                  as valor_desconto,

    -- ICMS
    p.aliquotaicms,
    op.subtotal::numeric(14,2) as valor_bc_icms,
    (
      op.subtotal
      * coalesce(p.aliquotaicms, 0) / 100
    )::numeric(14,2) as valor_icms,

    -- PIS (herdado do produto; default para 07/0,00 se não preenchido)
    coalesce(p.cst_pis, '07')                       as cst_pis,
    coalesce(p.aliquota_pis, 0)::numeric(5,2)       as aliquota_pis,
    0::numeric(14,2)                                as valor_pis,   -- se quiser, pode calcular depois

    -- COFINS (herdado do produto; default para 07/0,00 se não preenchido)
    coalesce(p.cst_cofins, '07')                    as cst_cofins,
    coalesce(p.aliquota_cofins, 0)::numeric(5,2)    as aliquota_cofins,
    0::numeric(14,2)                                as valor_cofins, -- idem

    -- CST genérico de ICMS (espelho do produto)
    p.cst
  from nfe n
  join ordemservico os on os.id = n.ordemservicoid
  join osproduto op on op.ordemservicoid = os.id
  join produto p on p.id = op.produtoid
  where n.id = p_nfe_id;

  --------------------------------------------------------------------
  -- 4) Opcional: se quiser garantir pelo menos 1 item, pode validar aqui
  --------------------------------------------------------------------
  if not exists (select 1 from nfe_item where nfe_id = p_nfe_id) then
    raise exception
      'Nenhum item foi gerado em nfe_item para a NF-e % (ordemservicoid=%).',
      p_nfe_id, v_nfe.ordemservicoid;
  end if;

end;




preencher_itens_nfe_de_venda

declare
  v_nfe record;
begin
  -- 1) Verifica NFE e vínculo com venda
  select * into v_nfe
  from public.nfe
  where id = p_nfe_id;

  if not found then
    raise exception 'NF-e % não encontrada na tabela nfe', p_nfe_id;
  end if;

  if v_nfe.vendaid is null then
    raise exception 'NF-e % não está vinculada a uma venda (vendaid nulo).', p_nfe_id;
  end if;

  -- 2) Remove itens anteriores
  delete from public.nfe_item
  where nfe_id = p_nfe_id;

  -- 3) Insere itens da VENDA (vendaproduto) na nfe_item
  insert into public.nfe_item (
    nfe_id,
    n_item,
    produtoid,
    descricao,
    ncm,
    cfop,
    csosn,
    cest,
    unidade,
    quantidade,
    valor_unitario,
    valor_total,
    valor_desconto,
    aliquotaicms,
    valor_bc_icms,
    valor_icms,
    cst_pis,
    aliquota_pis,
    valor_pis,
    cst_cofins,
    aliquota_cofins,
    valor_cofins,
    cst
  )
  select
    n.id as nfe_id,
    row_number() over (order by vp.id) as n_item,

    p.id as produtoid,
    coalesce(p.titulo, p.descricao) as descricao,
    p.ncm,
    coalesce(p.cfop, '5102') as cfop,
    p.csosn,
    p.cest,
    p.unidade,

    vp.quantidade::numeric(14,4) as quantidade,

    case
      when vp.quantidade::numeric > 0 then
        (vp.valor_total::numeric / vp.quantidade::numeric)::numeric(14,10)
      else
        vp.valor_total::numeric::numeric(14,10)
    end as valor_unitario,

    vp.valor_total::numeric(14,2) as valor_total,
    coalesce(vp.valor_desconto, 0)::numeric(14,2) as valor_desconto,

    -- ICMS
    p.aliquotaicms,
    vp.valor_total::numeric(14,2) as valor_bc_icms,
    (
      vp.valor_total::numeric
      * coalesce(p.aliquotaicms, 0) / 100
    )::numeric(14,2) as valor_icms,

    -- PIS
    coalesce(p.cst_pis, '07') as cst_pis,
    coalesce(p.aliquota_pis, 0)::numeric(5,2) as aliquota_pis,
    0::numeric(14,2) as valor_pis,

    -- COFINS
    coalesce(p.cst_cofins, '07') as cst_cofins,
    coalesce(p.aliquota_cofins, 0)::numeric(5,2) as aliquota_cofins,
    0::numeric(14,2) as valor_cofins,

    -- CST genérico
    p.cst
  from public.nfe n
  join public.venda v on v.id = n.vendaid
  join public.vendaproduto vp on vp.venda_id = v.id
  join public.produto p on p.id = vp.produtoid
  where n.id = p_nfe_id;

  if not exists (select 1 from public.nfe_item where nfe_id = p_nfe_id) then
    raise exception 'Nenhum item foi gerado em nfe_item para a NF-e % (vendaid=%).',
      p_nfe_id, v_nfe.vendaid;
  end if;
end;


reaplicar_baixa_estoque_os

declare
  r record;
  q_baixada int;
  delta int;
begin
  -- Para cada item ATUAL do orçamento
  for r in
    select p.produtoid, p.quantidade
      from public.osproduto p
     where p.ordemservicoid = p_os_id
  loop
    select b.quantidade into q_baixada
      from public.osproduto_baixa b
     where b.ordemservicoid = p_os_id
       and b.produtoid = r.produtoid;

    if q_baixada is null then
      delta := r.quantidade; -- primeira baixa
    else
      delta := r.quantidade - q_baixada; -- diferença desde a última aplicação
    end if;

    if delta > 0 then
      -- precisa baixar mais (consumir estoque)
      update public.produto
         set estoque = estoque - delta
       where id = r.produtoid
         and estoque >= delta;
      if not found then
        raise exception 'Estoque insuficiente para o produto % (necessário: %, OS %)', r.produtoid, delta, p_os_id
          using errcode = 'P0001';
      end if;

      insert into public.osproduto_baixa (ordemservicoid, produtoid, quantidade)
      values (p_os_id, r.produtoid, r.quantidade)
      on conflict (ordemservicoid, produtoid) do update
        set quantidade = excluded.quantidade;

    elsif delta < 0 then
      -- precisa devolver parte (reduziu quantidade no orçamento)
      update public.produto
         set estoque = estoque + (-delta)
       where id = r.produtoid;

      insert into public.osproduto_baixa (ordemservicoid, produtoid, quantidade)
      values (p_os_id, r.produtoid, r.quantidade)
      on conflict (ordemservicoid, produtoid) do update
        set quantidade = excluded.quantidade;
    end if;
  end loop;

  -- Itens que foram REMOVIDOS do orçamento: estorna tudo e apaga controle
  for r in
    select b.produtoid, b.quantidade
      from public.osproduto_baixa b
     where b.ordemservicoid = p_os_id
       and not exists (
         select 1 from public.osproduto p
          where p.ordemservicoid = p_os_id
            and p.produtoid = b.produtoid
       )
  loop
    update public.produto
       set estoque = estoque + r.quantidade
     where id = r.produtoid;

    delete from public.osproduto_baixa
     where ordemservicoid = p_os_id
       and produtoid      = r.produtoid;
  end loop;
end


recalcular_comissao_osservico
declare
  v_subtotal numeric;
  v_qtd int;
begin
  select coalesce(s.subtotal, 0)
    into v_subtotal
  from public.osservico s
  where s.ordemservicoid = p_ordemservicoid
    and s.servicoid = p_servicoid;

  select count(*)
    into v_qtd
  from public.osservico_realizador r
  where r.ordemservicoid = p_ordemservicoid
    and r.servicoid = p_servicoid;

  if v_qtd <= 0 then
    return;
  end if;

  update public.osservico_realizador r
  set
    valor_base = round(v_subtotal / v_qtd, 2),
    valor_comissao = round((v_subtotal / v_qtd) * coalesce(r.comissao_percent_aplicada, 0) / 100.0, 2),
    updated_at = now()
  where r.ordemservicoid = p_ordemservicoid
    and r.servicoid = p_servicoid;
end;

set_checklist_modelo_updated_at

begin
  new.atualizado_em := now();
  return new;
end 

tg_recalc_comissao_osservico_on_subtotal
begin
  perform public.recalcular_comissao_osservico(new.ordemservicoid, new.servicoid);
  return new;
end;

tg_recalc_comissao_osservico_realizador
begin
  perform public.recalcular_comissao_osservico(
    coalesce(new.ordemservicoid, old.ordemservicoid),
    coalesce(new.servicoid, old.servicoid)
  );

  return coalesce(new, old);
end;

tg_set_comissao_percent_aplicada
begin
  if new.comissao_percent_aplicada is null then
    select coalesce(u.comissao_percent, 0)
      into new.comissao_percent_aplicada
    from public.usuario u
    where u.id = new.usuarioid;
  end if;

  new.updated_at = now();
  return new;
end;

to_mercosul_equivalente

  select
    case
      -- placa antiga: ABC1234 -> ABC1C34 (0->A ... 9->J)
      when p ~ '^[A-Z]{3}[0-9]{4}$' then
        substr(p,1,3) ||
        substr(p,4,1) ||
        chr(65 + cast(substr(p,5,1) as int)) ||
        substr(p,6,2)

      -- já no padrão novo (Mercosul): mantém
      when p ~ '^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$' then
        p

      else null
    end;


trg_os_status_estornar
begin
  -- Quando a OS for recusada, devolve tudo que já foi baixado
  if new.status = 'CANCELADO' and (old.status is distinct from 'CANCELADO') then
    perform public.estornar_baixa_estoque_os(new.id);
  end if;
  return new;
end

-- ENUMS -- (ALGUNS NÃO ESTÃO SENDO UTILIZADOS)

banco_tipo	CORRENTE, POUPANCA, DIGITAL, PAGAMENTO, SALARIO, EMPRESARIAL

categoria_transacao	SERVICO, PRODUTO, TRANSPORTE_LOGISTICA, COMISSAO_REPASSE, TRANSFERENCIA, ALUGUEL, EQUIPAMENTO_FERRAMENTA, OUTROS, PECA, SALARIO, IMPOSTO_TAXA, UTILIDADE, ORDEM_SERVICO, VENDA

cliente_rank	EXCELENTE, ALTO, NORMAL, BAIXO

enum_alvo_reparo	VEICULO, PECA

enum_ambiente_nfe	HOMOLOGACAO, PRODUCAO

enum_estoque_status_produto	OK, BAIXO, CRITICO, SEM_ESTOQUE

enum_modelo_nfe	NFE, NFCE

enum_prioridade_os	BAIXA, NORMAL, ALTA

enum_status_aprovacao	PENDENTE, APROVADA, REPROVADA

enum_status_checklist	OK, ALERTA, FALHA

enum_status_cliente	ATIVO, INATIVO, PENDENTE

enum_status_nfe	RASCUNHO, ASSINADA, ENVIADA, AUTORIZADA, REJEITADA, CANCELADA, PENDENTE_ENVIO, DENEGADA

enum_status_os	ORCAMENTO, EM_ANDAMENTO, PAGAMENTO, CONCLUIDO, CANCELADO, APROVACAO_ORCAMENTO, ORCAMENTO_APROVADO, ORCAMENTO_RECUSADO, AGUARDANDO_CHECKLIST, SEM_COBRANCA

enum_status_venda	ABERTA, PAGAMENTO, FINALIZADA, CANCELADA, PENDENTE, PAGO, AUTORIZADO, CANCELADO

enum_tipo_desconto_venda	PORCENTAGEM, FIXO

enum_tipo_os	MANUTENCAO, REVISAO, INSTALACAO, DIAGNOSTICO

enum_tipo_pagamento	DINHEIRO, CARTAO, PIX, BOLETO, TRANSFERENCIA

enum_tipomovimentacao	ENTRADA, SAIDA, AJUSTE

enum_tipopessoa	FISICA, JURIDICA

estoque_status	OK, BAIXO, CRITICO, SEM_ESTOQUE

grupo_produto	MOTOR, INJECAO ELETRONICA, IGNICAO, ARREFECIMENTO, AR CONDICIONADO/CLIMATIZACAO, LUBRIFICANTES E FLUIDOS, FILTROS, TRANSMISSAO, EMBREAGEM, DIFERENCIAL E EIXOS, DIRECAO, SUSPENSAO, FREIOS, PNEUS E RODAS, ESCAPAMENTO, ELETRICA, BATERIAS, ILUMINACAO/SINALIZACAO, SENSORES E ATUADORES, INSTRUMENTOS DE MEDICAO, DIAGNOSTICO E SCANNER, CARROCERIA/LATARIA, VIDROS/RETROVISORES, INTERIOR ACABAMENTOS, JUNTAS/RETENTORES ORINGS, CORREIAS/TENSORES, CABOS E MANGUEIRAS, FIXADORES/PARAFUSOS, COLAS E SELANTES, ADITIVOS E QUIMICOS, ESTETICA/LIMPEZA, MATERIAIS/PINTURA, ABRASIVOS/LIXAS, FERRAMENTAS MANUAIS, FERRAMENTAS ELETRICAS PNEUMATICAS, EQUIPAMENTOS DE OFICINA, EPI/SEGURANCA, ORGANIZACAO/ARMAZENAGEM, ACESSORIOS, OUTROS

metodo_pagamento	PIX, CREDITO, DEBITO, BOLETO, TRANSFERENCIA, DINHEIRO

tipo_veiculo	MOTOS, CARROS, CAMINHOES

tipos_transacao	RECEITA, DESPESA, DEPOSITO, SAQUE

unidade_medida	UN, JGO, KIT, PAR, CX, PCT

user_role	ADMIN, USER

enum_canal_venda	PDV, ONLINE

enum_tipos_entrada	COMPRA_FORNECEDOR, COMPRA_PF, DEVOLUCAO

enum_staus_entrada	RASCUNHO, CONFIRMADA, CANCELADA



