CREATE TABLE IF NOT EXISTS public.cliente_endereco (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    cliente_id integer NOT NULL,
    nome_identificador text,
    cep text NOT NULL,
    logradouro text NOT NULL,
    numero text NOT NULL,
    complemento text,
    bairro text,
    cidade text NOT NULL,
    estado text NOT NULL,
    principal boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT cliente_endereco_pkey PRIMARY KEY (id),
    CONSTRAINT cliente_endereco_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.cliente(id)
);

CREATE TABLE IF NOT EXISTS public.favorito (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    cliente_id integer NOT NULL,
    produto_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT favorito_pkey PRIMARY KEY (id),
    CONSTRAINT favorito_cliente_id_produto_id_key UNIQUE (cliente_id, produto_id),
    CONSTRAINT favorito_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.cliente(id),
    CONSTRAINT favorito_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produto(id)
);

CREATE TABLE IF NOT EXISTS public.pedido (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    cliente_id integer NOT NULL,
    status text DEFAULT 'PENDENTE'::text NOT NULL,
    total numeric NOT NULL,
    data_pedido timestamp with time zone DEFAULT now(),
    forma_pagamento text,
    endereco_entrega_snapshot jsonb,
    CONSTRAINT pedido_pkey PRIMARY KEY (id),
    CONSTRAINT pedido_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.cliente(id)
);

CREATE TABLE IF NOT EXISTS public.item_pedido (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    pedido_id bigint NOT NULL,
    produto_id integer NOT NULL,
    quantidade integer NOT NULL,
    preco_unitario numeric NOT NULL,
    CONSTRAINT item_pedido_pkey PRIMARY KEY (id),
    CONSTRAINT item_pedido_pedido_id_fkey FOREIGN KEY (pedido_id) REFERENCES public.pedido(id),
    CONSTRAINT item_pedido_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produto(id)
);

CREATE TABLE IF NOT EXISTS public.nfse (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ordemservicoid integer,
    clienteid integer,
    empresaid integer,
    dataemissao timestamp with time zone DEFAULT now(),
    status character varying DEFAULT 'RASCUNHO'::character varying,
    referencia character varying,
    numero character varying,
    codigo_verificacao character varying,
    protocolo character varying,
    valor_total numeric DEFAULT 0,
    qr_code_url text,
    url_xml text,
    url_pdf text,
    erros jsonb,
    createdat timestamp with time zone DEFAULT now(),
    updatedat timestamp with time zone DEFAULT now(),
    CONSTRAINT nfse_pkey PRIMARY KEY (id),
    CONSTRAINT nfse_referencia_key UNIQUE (referencia),
    CONSTRAINT nfse_clienteid_fkey FOREIGN KEY (clienteid) REFERENCES public.cliente(id) ON DELETE SET NULL,
    CONSTRAINT nfse_empresaid_fkey FOREIGN KEY (empresaid) REFERENCES public.empresa(id) ON DELETE SET NULL,
    CONSTRAINT nfse_ordemservicoid_fkey FOREIGN KEY (ordemservicoid) REFERENCES public.ordemservico(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.vendaproduto_baixa (
    venda_id integer NOT NULL,
    produtoid integer NOT NULL,
    quantidade integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT vendaproduto_baixa_pkey PRIMARY KEY (venda_id, produtoid),
    CONSTRAINT vendaproduto_baixa_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.venda(id) ON DELETE CASCADE,
    CONSTRAINT vendaproduto_baixa_produtoid_fkey FOREIGN KEY (produtoid) REFERENCES public.produto(id)
);

ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS user_id uuid;

ALTER TABLE public.cliente_endereco OWNER TO postgres;
ALTER TABLE public.favorito OWNER TO postgres;
ALTER TABLE public.item_pedido OWNER TO postgres;
ALTER TABLE public.nfse OWNER TO postgres;
ALTER TABLE public.pedido OWNER TO postgres;
ALTER TABLE public.vendaproduto_baixa OWNER TO postgres;

ALTER TABLE public.cliente_endereco ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorito ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.item_pedido ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Endereços: Atualizar seus próprios" ON public.cliente_endereco FOR UPDATE USING ((cliente_id IN ( SELECT cliente.id FROM public.cliente WHERE (cliente.user_id = auth.uid()))));
CREATE POLICY "Endereços: Deletar seus próprios" ON public.cliente_endereco FOR DELETE USING ((cliente_id IN ( SELECT cliente.id FROM public.cliente WHERE (cliente.user_id = auth.uid()))));
CREATE POLICY "Endereços: Inserir seus próprios" ON public.cliente_endereco FOR INSERT WITH CHECK ((cliente_id IN ( SELECT cliente.id FROM public.cliente WHERE (cliente.user_id = auth.uid()))));
CREATE POLICY "Endereços: Ver seus próprios" ON public.cliente_endereco FOR SELECT USING ((cliente_id IN ( SELECT cliente.id FROM public.cliente WHERE (cliente.user_id = auth.uid()))));

CREATE POLICY "Favoritos: Gerenciar seus próprios" ON public.favorito USING ((cliente_id IN ( SELECT cliente.id FROM public.cliente WHERE (cliente.user_id = auth.uid()))));
CREATE POLICY "Favoritos: Ver seus próprios" ON public.favorito FOR SELECT USING ((cliente_id IN ( SELECT cliente.id FROM public.cliente WHERE (cliente.user_id = auth.uid()))));

CREATE POLICY "Pedidos: Inserir ao comprar" ON public.pedido FOR INSERT WITH CHECK ((cliente_id IN ( SELECT cliente.id FROM public.cliente WHERE (cliente.user_id = auth.uid()))));
CREATE POLICY "Pedidos: Ver seus próprios" ON public.pedido FOR SELECT USING ((cliente_id IN ( SELECT cliente.id FROM public.cliente WHERE (cliente.user_id = auth.uid()))));

CREATE POLICY "Itens Pedido: Inserir ao comprar" ON public.item_pedido FOR INSERT WITH CHECK ((pedido_id IN ( SELECT pedido.id FROM public.pedido WHERE (pedido.cliente_id IN ( SELECT cliente.id FROM public.cliente WHERE (cliente.user_id = auth.uid()))))));
CREATE POLICY "Itens Pedido: Ver seus próprios" ON public.item_pedido FOR SELECT USING ((pedido_id IN ( SELECT pedido.id FROM public.pedido WHERE (pedido.cliente_id IN ( SELECT cliente.id FROM public.cliente WHERE (cliente.user_id = auth.uid()))))));

GRANT ALL ON TABLE public.cliente_endereco TO anon;
GRANT ALL ON TABLE public.cliente_endereco TO authenticated;
GRANT ALL ON TABLE public.cliente_endereco TO service_role;
GRANT ALL ON TABLE public.favorito TO anon;
GRANT ALL ON TABLE public.favorito TO authenticated;
GRANT ALL ON TABLE public.favorito TO service_role;
GRANT ALL ON TABLE public.item_pedido TO anon;
GRANT ALL ON TABLE public.item_pedido TO authenticated;
GRANT ALL ON TABLE public.item_pedido TO service_role;
GRANT ALL ON TABLE public.nfse TO anon;
GRANT ALL ON TABLE public.nfse TO authenticated;
GRANT ALL ON TABLE public.nfse TO service_role;
GRANT ALL ON TABLE public.pedido TO anon;
GRANT ALL ON TABLE public.pedido TO authenticated;
GRANT ALL ON TABLE public.pedido TO service_role;
GRANT ALL ON TABLE public.vendaproduto_baixa TO anon;
GRANT ALL ON TABLE public.vendaproduto_baixa TO authenticated;
GRANT ALL ON TABLE public.vendaproduto_baixa TO service_role;

GRANT USAGE ON SEQUENCE public.cliente_endereco_id_seq TO anon;
GRANT USAGE ON SEQUENCE public.cliente_endereco_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.cliente_endereco_id_seq TO service_role;
GRANT USAGE ON SEQUENCE public.favorito_id_seq TO anon;
GRANT USAGE ON SEQUENCE public.favorito_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.favorito_id_seq TO service_role;
GRANT USAGE ON SEQUENCE public.item_pedido_id_seq TO anon;
GRANT USAGE ON SEQUENCE public.item_pedido_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.item_pedido_id_seq TO service_role;
GRANT USAGE ON SEQUENCE public.nfse_id_seq TO anon;
GRANT USAGE ON SEQUENCE public.nfse_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.nfse_id_seq TO service_role;
GRANT USAGE ON SEQUENCE public.pedido_id_seq TO anon;
GRANT USAGE ON SEQUENCE public.pedido_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.pedido_id_seq TO service_role;
