create table if not exists public.osanexo (
  id bigint generated by default as identity not null,
  ordemservicoid integer not null,
  nome text not null,
  tipo text,
  tamanho integer,
  url text not null,
  path text not null,
  descricao text,
  createdat timestamp with time zone not null default now(),
  constraint osanexo_pkey primary key (id)
);

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conname = 'osanexo_ordemservicoid_fkey'
  ) then
    alter table public.osanexo
      add constraint osanexo_ordemservicoid_fkey
      foreign key (ordemservicoid)
      references public.ordemservico(id)
      on delete cascade;
  end if;
end $$;

create index if not exists osanexo_ordemservicoid_idx
  on public.osanexo using btree (ordemservicoid);

create unique index if not exists osanexo_path_uq
  on public.osanexo using btree (path);

grant all on table public.osanexo to anon;
grant all on table public.osanexo to authenticated;
grant all on table public.osanexo to service_role;

grant all on sequence public.osanexo_id_seq to anon;
grant all on sequence public.osanexo_id_seq to authenticated;
grant all on sequence public.osanexo_id_seq to service_role;

insert into storage.buckets (id, name, owner, public, avif_autodetection, file_size_limit)
values ('os_anexos', 'os_anexos', null, true, null, null)
on conflict (id) do nothing;
