-- Migration: Unify NFe Schema for Entry Invoices
-- Date: 2026-01-30

-- 0. Ensure the current entry schema exists. Some baselines still have the
-- legacy produtoentrada table, while the application expects entrada/entradaitens.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_tipos_entrada') THEN
        CREATE TYPE public.enum_tipos_entrada AS ENUM ('COMPRA_FORNECEDOR', 'COMPRA_PF', 'DEVOLUCAO');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_status_entrada') THEN
        CREATE TYPE public.enum_status_entrada AS ENUM ('RASCUNHO', 'CONFIRMADA', 'CANCELADA');
    END IF;
END $$;

DROP TABLE IF EXISTS public.produtoentrada CASCADE;

CREATE TABLE IF NOT EXISTS public.entrada (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    fornecedorid integer,
    fiscal boolean DEFAULT false NOT NULL,
    notachave text,
    tipo public.enum_tipos_entrada DEFAULT 'COMPRA_FORNECEDOR'::public.enum_tipos_entrada NOT NULL,
    status public.enum_status_entrada DEFAULT 'RASCUNHO'::public.enum_status_entrada NOT NULL,
    CONSTRAINT produtoentrada_pkey PRIMARY KEY (id),
    CONSTRAINT produtoentrada_fornecedorid_fkey FOREIGN KEY (fornecedorid) REFERENCES public.fornecedor(id)
);

CREATE TABLE IF NOT EXISTS public.entradaitens (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    produto_id integer NOT NULL,
    unidade public.unidade_medida DEFAULT 'UN'::public.unidade_medida NOT NULL,
    quantidade numeric NOT NULL,
    precovenda numeric NOT NULL,
    entrada_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    ncm text,
    cest text,
    csosn text,
    referencia text,
    titulo text,
    "cClassTrib" text,
    "cstIbs" text,
    "cstCbs" text,
    cst text,
    aliquotaicms numeric,
    cfop text,
    cst_pis text,
    aliquota_pis numeric,
    cst_cofins text,
    aliquota_cofins numeric,
    CONSTRAINT entradaitens_pkey PRIMARY KEY (id),
    CONSTRAINT entradaitens_entrada_id_fkey FOREIGN KEY (entrada_id) REFERENCES public.entrada(id) ON DELETE CASCADE,
    CONSTRAINT entradaitens_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produto(id)
);

ALTER TABLE public.entrada OWNER TO postgres;
ALTER TABLE public.entradaitens OWNER TO postgres;

GRANT ALL ON TABLE public.entrada TO anon;
GRANT ALL ON TABLE public.entrada TO authenticated;
GRANT ALL ON TABLE public.entrada TO service_role;
GRANT ALL ON TABLE public.entradaitens TO anon;
GRANT ALL ON TABLE public.entradaitens TO authenticated;
GRANT ALL ON TABLE public.entradaitens TO service_role;
GRANT USAGE ON SEQUENCE public.entradaitens_id_seq TO anon;
GRANT USAGE ON SEQUENCE public.entradaitens_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.entradaitens_id_seq TO service_role;

-- 1. Make clienteid nullable to support invoices without a client (Entry)
ALTER TABLE public.nfe ALTER COLUMN clienteid DROP NOT NULL;

-- 2. Add columns for Entry flow
ALTER TABLE public.nfe ADD COLUMN IF NOT EXISTS fornecedorid integer REFERENCES fornecedor(id);
ALTER TABLE public.nfe ADD COLUMN IF NOT EXISTS entradaid bigint REFERENCES entrada(id);

-- 3. Add constraint to ensure either Client or Supplier is present, but not both
-- Wrap in DO block to avoid error if constraint already exists
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_nfe_destinatario') THEN
        ALTER TABLE public.nfe ADD CONSTRAINT ck_nfe_destinatario CHECK (
            (clienteid IS NOT NULL AND fornecedorid IS NULL) OR 
            (clienteid IS NULL AND fornecedorid IS NOT NULL)
        );
    END IF;
END $$;
